export const stationNames = ["Abancourt",
    "Abbaretz",
    "Abbeville",
    "Ablon-sur-Seine",
    "Accolay",
    "Achères Grand Cormier",
    "Achères Ville",
    "Acheux - Franleu",
    "Achicourt",
    "Achiet-le-Grand",
    "Achy",
    "Aéroport Charles de Gaulle 1",
    "Aéroport Charles de Gaulle 2 TGV",
    "Agay",
    "Agde",
    "Agen",
    "Agonac",
    "Aguilcourt - Variscourt",
    "Aigrefeuille le Thou",
    "Aiguebelette-le-Lac",
    "Aiguebelle",
    "Aigueperse",
    "Aigues Vives",
    "Aigues-Mortes",
    "Aiguillon",
    "Aillevillers",
    "Ailly-sur-Noye",
    "Ailly-sur-Somme",
    "Aimargues",
    "Aime - La Plagne",
    "Aiserey",
    "Aix la Marsalouse",
    "Aix-en-Provence",
    "Aix-en-Provence TGV",
    "Aixe-sur-Vienne",
    "Aix-les-Bains le Revard",
    "Alaï",
    "Albens",
    "Albert",
    "Albertville",
    "Albi",
    "Albi Madeleine",
    "Albias",
    "Albigny - Neuville",
    "Alençon",
    "Alès",
    "Alet-les-Bains",
    "Allassac",
    "Allée de la Tour Rendez-Vous",
    "Allée Royale T13",
    "Allenc",
    "Alles-sur-Dordogne",
    "Alleyras",
    "Altkirch",
    "Amagne - Lucquy",
    "Ambazac",
    "Ambérieu-en-Bugey",
    "Ambilly",
    "Amboise",
    "Ambronay - Priay",
    "Amiens",
    "Amifontaine",
    "Amilly Ouerray",
    "Amplepuis",
    "Ancenis",
    "Anchamps",
    "Anché - Voulon",
    "Ancy-sur-Moselle",
    "Andelot-en-Montagne",
    "Andrésy",
    "Andrézieux-Bouthéon",
    "Angers Maître École",
    "Angers Saint-Laud",
    "Angerville",
    "Angoulême",
    "Angoulins sur Mer",
    "Anizy - Pinon",
    "Annappes",
    "Annecy",
    "Annemasse",
    "Anor",
    "Anse",
    "Anstaing",
    "Anthéor Cap Roux",
    "Antibes",
    "Anvin",
    "Apach",
    "Appilly",
    "Arbanats",
    "Arbois",
    "Arcachon",
    "Arc-et-Senans",
    "Arches",
    "Arcy-sur-Cure",
    "Arenc Euroméditerranée",
    "Arengosse",
    "Argelès-sur-Mer",
    "Argentan",
    "Argenteuil",
    "Argentière",
    "Argenton-sur-Creuse",
    "Arles",
    "Arleux",
    "Armentières",
    "Arnage",
    "Arnèke",
    "Arpajon",
    "Arras",
    "Arrou",
    "Ars-sur-Moselle",
    "Artenay",
    "Artix",
    "Arvant",
    "Ascq",
    "Asnières-sur-Seine",
    "Aspres-sur-Buëch",
    "Assat",
    "Assier",
    "Athis-Mons",
    "Aubagne",
    "Aubazines - Saint-Hilaire",
    "Aubergenville Élisabethville",
    "Aubiat",
    "Aubie - Saint-Antoine",
    "Aubiet",
    "Aubigné-Racan",
    "Aubigny-au-Bac",
    "Aubigny-en-Artois",
    "Aubin",
    "Aubin-Saint-Vaast",
    "Auboué",
    "Aubrives",
    "Aubusson",
    "Auch",
    "Auchy-lès-Hesdin",
    "Audrieu",
    "Audruicq",
    "Audun-le-Roman",
    "Auffay",
    "Augy Vaux",
    "Aulnat Aéroport",
    "Aulnay-sous-Bois",
    "Aulnoye-Aymeries",
    "Aumale",
    "Aumont-Aubrac",
    "Auneau",
    "Auray",
    "Aurec-sur-Loire",
    "Aurillac",
    "Auterive",
    "Autun",
    "Auvers-sur-Oise",
    "Auxerre Saint-Gervais",
    "Auxonne",
    "Avallon",
    "Avenay",
    "Avenue du Président Kennedy MRF",
    "Avenue Foch",
    "Avenue Henri Martin",
    "Avesnelles",
    "Avesnes-sur-Helpe",
    "Avignon Centre",
    "Avignon TGV",
    "Avignon TGV",
    "Avignonet-Lauragais",
    "Avion",
    "Avord",
    "Avoudrey",
    "Avranches",
    "Avrechy",
    "Ax-les-Thermes",
    "Ay",
    "Aytré Plage",
    "Azay-le-Rideau",
    "Azay-sur-Cher",
    "Azerailles",
    "Babinière",
    "Baccarat",
    "Bagnac-sur-Célé",
    "Bagneaux-sur-Loing",
    "Bagnols - Chadenet",
    "Bagnols-sur-Cèze",
    "Baillargues",
    "Bailleau-le-Pin",
    "Bailleul",
    "Bailleul-Sir-Berthoult",
    "Bailly T13",
    "Bailly T13",
    "Bains-les-Bains",
    "Bainville-sur-Madon",
    "Baisieux",
    "Balagny Saint-Épin",
    "Balbigny",
    "Ballancourt-sur-Essonne",
    "Ballan-Miré",
    "Ballersdorf",
    "Banassac - La Canourgue",
    "Bandol",
    "Bannalec",
    "Bantzenheim",
    "Banyuls-sur-Mer",
    "Baraqueville Carcenac Peyralès",
    "Barentin",
    "Barenton-Bugny",
    "Barjac",
    "Bar-le-Duc",
    "Baroncourt",
    "Barr",
    "Barsac",
    "Barsanges",
    "Bar-sur-Aube",
    "Bartenheim",
    "Bas - Monistrol-sur-Loire",
    "Bas Évette",
    "Base Aérienne",
    "Basse-Ham",
    "Bassens",
    "Batz-sur-Mer",
    "Baule",
    "Baume-les-Dames",
    "Bauvin - Provin",
    "Bayard",
    "Bayeux",
    "Bayon",
    "Bayonne",
    "Bazancourt",
    "Baziège",
    "Béard",
    "Beau Marais",
    "Beaucaire",
    "Beaucroissant",
    "Beaugency",
    "Beaulieu-sur-Mer",
    "Beaumont-le-Roger",
    "Beaune",
    "Beaurainville",
    "Beautiran",
    "Beauvais",
    "Beauvoir-sur-Niort",
    "Beauvoisin",
    "Beauzac",
    "Bécon les Bruyères",
    "Bédarieux",
    "Bédarrides",
    "Bedous",
    "Bègles",
    "Beillant",
    "Belfort",
    "Belfort - Montbéliard TGV",
    "Bellac",
    "Bellegarde",
    "Belle-Isle - Bégard",
    "Bellenaves",
    "Belleville",
    "Belleville sur Sâone",
    "Belleville-sur-Vie",
    "Bellevue",
    "Bellignat",
    "Bellou-en-Houlme",
    "Belloy - Saint-Martin",
    "Belvès",
    "Belvezet",
    "Belz - Ploemel",
    "Bena Fanes",
    "Bénesse-Maremne",
    "Bénestroff",
    "Benfeld",
    "Bengy-sur-Craon",
    "Béning",
    "Bergerac",
    "Bergues",
    "Berlaimont",
    "Bernay",
    "Berre",
    "Bersac-sur-Rivalier",
    "Berthelming",
    "Bertrichamps",
    "Bertry",
    "Besançon Franche-Comté TGV",
    "Besançon Mouillère",
    "Besançon Viotte",
    "Beslé",
    "Bessancourt",
    "Bessay-sur-Allier",
    "Bessèges",
    "Bétaille",
    "Béthune",
    "Betton",
    "Beuvrages",
    "Beuvry lès Béthune",
    "Beynes",
    "Beynost",
    "Béziers",
    "Biache-Saint-Vaast",
    "Biarritz",
    "Bibliothèque François Mitterrand",
    "Bidarray Pont Noblia",
    "Bidos",
    "Bièvres",
    "Biffontaine",
    "Biganos Facture",
    "Bigny",
    "Billy-Montigny",
    "Biot",
    "Bischheim",
    "Bischoffsheim",
    "Bischwiller",
    "Bitschwiller-lès-Thann",
    "Blainville - Damelevières",
    "Blaisy-Bas",
    "Blangy-Glisy",
    "Blangy-sur-Bresle",
    "Blangy-sur-Ternoise",
    "Blanquefort",
    "Blanzy",
    "Blaye",
    "Bléré - La Croix",
    "Blois - Chambord",
    "Blonville-sur-Mer - Benerville",
    "Boën-sur-Lignon",
    "Bogny-sur-Meuse",
    "Bohain-en-Vermandois",
    "Boigneville",
    "Bois-Colombes",
    "Bois-d'Oingt - Légny",
    "Bois-le-Roi",
    "Boisleux-au-Mont",
    "Boisseaux",
    "Boisset",
    "Boissise-le-Roi",
    "Boissy-l'Aillerie",
    "Bolbec - Nointot",
    "Bollène La Croisière",
    "Bollwiller",
    "Bologne",
    "Bolquère - Eyne",
    "Bondy",
    "Bonnemain",
    "Bonneval",
    "Bonneville",
    "Bonnières-sur-Seine",
    "Bons-en-Chablais",
    "Bonson",
    "Boran-sur-Oise",
    "Bordeaux Saint-Jean",
    "Bords",
    "Bornel - Belle-Église",
    "Bouaye",
    "Boucau",
    "Bouchain",
    "Boucoiran-et-Nozières",
    "Bouffémont - Moisselles",
    "Bougival",
    "Boulainvilliers",
    "Boulazac",
    "Boulogne Tintelleries",
    "Boulogne-sur-Mer",
    "Boulouris sur Mer",
    "Bouray",
    "Bourbourg",
    "Bourg-Bruche",
    "Bourg-en-Bresse",
    "Bourges",
    "Bourg-Lastic - Messeix",
    "Bourg-Madame",
    "Bourgneuf-en-Retz",
    "Bourgoin-Jallieu",
    "Bourg-Saint-Maurice",
    "Bourgtheroulde - Thuit-Hébert",
    "Bournezeau",
    "Bourron-Marlotte - Grez",
    "Bourth",
    "Boussay - La Bruffière",
    "Boussens",
    "Boussy-Saint-Antoine",
    "Bouthéon",
    "Boutigny-sur-Essonne",
    "Bouy",
    "Bouzonville",
    "Boves",
    "Bram",
    "Brandérion",
    "Brassac-les-Mines - Sainte-Florine",
    "Brax - Léguevin",
    "Brazey-en-Plaine",
    "Bréauté - Beuzeville",
    "Brebières",
    "Breil-sur-Roya",
    "Breitenbach",
    "Brélidy - Plouëc",
    "Bressuire",
    "Brest",
    "Breteil",
    "Bretenoux - Biars",
    "Breteuil-Embranchement",
    "Bretigny - Norges",
    "Brétigny-sur-Orge",
    "Bretoncelles",
    "Bretteville - Norrey",
    "Breuil - Romain",
    "Breuillet - Bruyères-le-Châtel",
    "Breuillet Village",
    "Bréval",
    "Briançon",
    "Briare",
    "Brignac",
    "Brignais",
    "Brignoud",
    "Brimeux",
    "Brion - Laizy",
    "Brion - Montréal-la-Cluse",
    "Brionne",
    "Brioude",
    "Briouze",
    "Brive-la-Gaillarde",
    "Broons",
    "Brou",
    "Broye",
    "Bruges",
    "Brumath",
    "Brunémont",
    "Brunoy",
    "Bruyères",
    "Bruyères-sur-Oise",
    "Bruz",
    "Budelière-Chambon",
    "Bueil",
    "Bugeat",
    "Buire-sur-l'Ancre",
    "Bully - Grenay",
    "Buno - Gironville",
    "Busigny",
    "Bussac-Forêt",
    "Busseau sur Creuse",
    "Bussière-Galant",
    "Buzy en Béarn",
    "Byans-sur-Doubs",
    "Cadaujac",
    "Caen",
    "Caffiers",
    "Cagnes-sur-Mer",
    "Cahors",
    "Calais",
    "Calais - Fréthun",
    "Callac",
    "Calonne-Ricouart",
    "Cambo-les-Bains",
    "Cambrai",
    "Campagnac - Saint-Geniez",
    "Campagne-sur-Aude",
    "Cannes",
    "Cannes La Bocca",
    "Cantin",
    "Cap-d'Ail",
    "Capdenac",
    "Capvern",
    "Carantilly - Marigny",
    "Carbonne",
    "Carcassonne",
    "Carentan",
    "Carhaix-Plouguer",
    "Carignan",
    "Carmaux",
    "Carnoët - Locarn",
    "Carnoles",
    "Carnoules",
    "Carpentras",
    "Carry-le-Rouet",
    "Casino Lacroix Laval",
    "Cassel",
    "Cassis",
    "Castelnaudary",
    "Castelnau-d'Estrétefonds",
    "Castelsarrasin",
    "Castillon-la-Bataille",
    "Castres",
    "Cattenières",
    "Caudéran Mérignac",
    "Caudrot",
    "Caudry",
    "Caulnes",
    "Caussade",
    "Cavaillon",
    "Cavignac",
    "Cazères",
    "Ceilhes - Roqueredonde",
    "Ceintrey",
    "Cenon",
    "Cerbère",
    "Cercottes",
    "Cercy-la-Tour",
    "Cérences",
    "Cergy le Haut",
    "Cergy Préfecture",
    "Cergy Saint-Christophe",
    "Cerizay",
    "Cernay (Haut-Rhin)",
    "Cernay (Val-d'Oise)",
    "Cérons",
    "Cessieu",
    "Cesson",
    "Cesson-Sévigné",
    "Ceyzériat",
    "Cézy",
    "Chabanais",
    "Chabenet",
    "Châbons",
    "Chabris",
    "Chagny",
    "Chaingy Fourneaux Plage",
    "Chalais",
    "Challans",
    "Chalonnes-sur-Loire",
    "Châlons-en-Champagne",
    "Chalon-sur-Saône",
    "Chamalières-sur-Loire",
    "Chamarande",
    "Chambéry - Challes-les-Eaux",
    "Chamblet",
    "Chambly",
    "Chamborigaud",
    "Chambourg-sur-Indre",
    "Chamelet",
    "Chamonix Aiguille du Midi",
    "Chamonix-Mont-Blanc",
    "Chamousset",
    "Champ de Courses d'Enghien",
    "Champ de Mars Tour Eiffel",
    "Champagné",
    "Champagne-Ardenne TGV",
    "Champagne-sur-Oise",
    "Champagne-sur-Seine",
    "Champagney",
    "Champagnole",
    "Champagnole Paul-Émile Victor",
    "Champbenoist - Poigny",
    "Champigneulles",
    "Champigny sur Yonne",
    "Champs - Saint-Bris",
    "Champtocé-sur-Loire",
    "Chanac",
    "Chandieu Toussieu",
    "Changis - Saint-Jean",
    "Chanteloup-les-Vignes",
    "Chantenay",
    "Chantenay-Saint-Imbert",
    "Chantilly - Gouvieux",
    "Chantonnay",
    "Chapeauroux",
    "Chaponost",
    "Chaponval",
    "Charbonnières-les-Bains",
    "Charleville-Mézières",
    "Charmes",
    "Chars",
    "Chartres",
    "Chartrettes",
    "Chasseneuil-du-Poitou",
    "Chasseneuil-sur-Bonnieure",
    "Chasseradès",
    "Chasse-sur-Rhône",
    "Château-Arnoux-Saint-Auban",
    "Châteaubourg",
    "Châteaubriant",
    "Châteaubriant Tram Train",
    "Château-du-Loir",
    "Châteaudun",
    "Château-Gaillard",
    "Château-l'Évêque",
    "Châteaulin",
    "Châteauneuf - Bujaleuf",
    "Châteauneuf-sur-Charente",
    "Châteauneuf-sur-Cher",
    "Château-Renault",
    "Châteauroux",
    "Château-Thierry",
    "Châtel - Nomexy",
    "Châtelaillon-Plage",
    "Châtelaudren - Plouagat",
    "Châtel-Censoir",
    "Châtellerault",
    "Châtillon d'Azergues",
    "Chauffailles",
    "Chaugey",
    "Chaulnes",
    "Chaumont",
    "Chaumont-en-Vexin",
    "Chauny",
    "Chaux-des-Crotenay",
    "Chavagnes-les-Redoux",
    "Chaville - Vélizy",
    "Chaville Rive Droite",
    "Chaville Rive Gauche",
    "Chazay - Marcilly",
    "Chedde",
    "Chef-du-Pont-Ste-Mère",
    "Cheilly-lès-Maranges",
    "Chelles - Gournay",
    "Chemillé-en-Anjou",
    "Chemilly - Appoigny",
    "Chemin d'Antony",
    "Chenevières",
    "Chenonceaux",
    "Chépy - Valines",
    "Cherbourg",
    "Chessy",
    "Chevaigné",
    "Chevillon",
    "Chevilly",
    "Chevrières",
    "Chézy-sur-Marne",
    "Chilly-Mazarin",
    "Chindrieux",
    "Chinon",
    "Chirac",
    "Chissay-en-Touraine",
    "Chocques",
    "Choisy-le-Roi",
    "Cholet",
    "Chorges",
    "Chouzy-sur-Cisse",
    "Cinq-Mars-la-Pile",
    "Cintegabelle",
    "Cires-lès-Mello",
    "Ciry-le-Noble",
    "Civrieux-d'Azergues",
    "Cize - Bolozon",
    "Clacy - Mons",
    "Clamart",
    "Clamecy",
    "Clelles - Mens",
    "Clères",
    "Clermont de l'Oise",
    "Clermont La Pardieu",
    "Clermont La Rotonde",
    "Clermont-en-Argonne",
    "Clermont-Ferrand",
    "Clerval",
    "Clichy - Levallois",
    "Clion sur Seugne",
    "Clisson",
    "Cloyes-sur-le-Loir",
    "Cluses",
    "Coarraze - Nay",
    "Coat Guégan",
    "Cobrieux",
    "Cognac",
    "Coignières",
    "Collioure",
    "Collonges - Fontaines",
    "Collonges-lès-Premières",
    "Colmar",
    "Colmar Mésanges",
    "Colmar Saint-Joseph",
    "Colombes",
    "Colombier-Fontaine",
    "Colomiers",
    "Colomiers Lycée International",
    "Colroy - Lubine",
    "Combourg",
    "Combs-la-Ville - Quincy",
    "Comines",
    "Commentry",
    "Commercy",
    "Compans",
    "Compiègne",
    "Conches-en-Ouche",
    "Condat - Le Lardin",
    "Condé-sur-Huisne",
    "Conflans - Jarny",
    "Conflans Fin d'Oise",
    "Conflans-Sainte-Honorine",
    "Conlie",
    "Connerré - Beillé",
    "Contrexéville",
    "Corbehem",
    "Corbeil-Essonnes",
    "Corbie",
    "Corbigny",
    "Corcieux Vanémont",
    "Corcy",
    "Cordemais",
    "Cordes - Vindrac",
    "Cordesse - Igornay",
    "Corgoloin",
    "Cormeilles-en-Parisis",
    "Cormery",
    "Cornil",
    "Coron de Méricourt",
    "Corps-Nuds",
    "Corrèze",
    "Corseul - Languenan",
    "Cosne-sur-Loire",
    "Coucy-lès-Eppes",
    "Coudekerque-Branche",
    "Couëron",
    "Couffoulens - Leuc",
    "Couilly - Saint-Germain - Quincy",
    "Coulanges-sur-Yonne",
    "Couliboeuf",
    "Coulommiers",
    "Courbevoie",
    "Courcay - Tauxigny",
    "Courcelles-le-Comte",
    "Courcelles-sur-Nied",
    "Courcy - Brimont",
    "Courghain",
    "Coursan",
    "Courtalain - Saint-Pellerin",
    "Courthézon",
    "Courville-sur-Eure",
    "Cousance",
    "Coussac-Bonneval",
    "Coutances",
    "Coutras",
    "Couze",
    "Couzon-au-Mont-d'Or",
    "Cramoisy",
    "Cransac",
    "Cravant - Bazarnes",
    "Crêches-sur-Saône",
    "Crécy-la-Chapelle",
    "Creil",
    "Crépieux la Pape",
    "Crépy - Couvron",
    "Crépy-en-Valois",
    "Crest",
    "Créteil Pompadour",
    "Creysse-Mouleydier",
    "Crissé",
    "Croix - Wasquehal",
    "Croix d'Hins",
    "Croix du Prince",
    "Croix L'Allumette",
    "Croix Sainte",
    "Cros de Cagnes",
    "Crouy",
    "Crouy-sur-Ourcq",
    "Cubzac-les-Ponts",
    "Cuers - Pierrefeu",
    "Cugand",
    "Cuinchy",
    "Culmont - Chalindrey",
    "Culoz",
    "Curchy-Dreslincourt",
    "Dachstein",
    "Dambach-la-Ville",
    "Damiatte - Saint-Paul",
    "Dammartin - Juilly - Saint-Mard",
    "Dangé-Saint-Romain",
    "Danjoutin",
    "Dannemarie",
    "Dannemarie - Velesmes",
    "Dannes - Camiers",
    "Daours",
    "Dardilly Le Jubin",
    "Dardilly Les Mouilles",
    "Darsac",
    "Dax",
    "Decize",
    "Dégagnac",
    "Delle",
    "Deluz",
    "Denain",
    "Dercy - Froidmont",
    "Dettwiller",
    "Deuil - Montmagny",
    "Deûlémont",
    "Deville",
    "Diarville",
    "Die",
    "Diemeringen",
    "Dieppe",
    "Dieulouard",
    "Dieupentale",
    "Digoin",
    "Dijon",
    "Dijon Porte Neuve",
    "Dinan",
    "Dingé",
    "Diou",
    "Dirinon",
    "Dissay",
    "Dives-sur-Mer - Cabourg",
    "Dives-sur-Mer Port Guillaume",
    "Docelles - Cheniménil",
    "Dol-de-Bretagne",
    "Dole",
    "Dombasle-sur-Meurthe",
    "Domblans - Voiteur",
    "Domfront-en-Champagne",
    "Dommartin - Lissieu",
    "Dommartin - Remiencourt",
    "Domont",
    "Dompierre Sept Fons",
    "Dompierre-sur-Helpe",
    "Don - Sainghin",
    "Donchery",
    "Donges",
    "Donjeux",
    "Donzère",
    "Dordives",
    "Dorlisheim",
    "Dormans",
    "Douai",
    "Dourdan",
    "Dourdan La Forêt",
    "Dourges",
    "Douzillac",
    "Dracy-St-Loup",
    "Drancy",
    "Drap - Cantaron",
    "Drefféac",
    "Dreuil-lès-Amiens",
    "Dreux",
    "Drusenheim",
    "Druye",
    "Dugny - La Courneuve T11",
    "Dunkerque",
    "Duppigheim",
    "Durtol - Nohanent",
    "Duttlenheim",
    "Ebblinghem",
    "Ebersheim",
    "Ébersviller",
    "Échirolles",
    "École-Valentin",
    "Écommoy",
    "Écouché",
    "Écouen - Ézanville",
    "Écouflant",
    "Ecully - Tassin",
    "Égletons",
    "Égly",
    "Éguzon-Chantôme",
    "Eichhoffen",
    "Einvaux",
    "Elbeuf - Saint-Aubin",
    "Elne",
    "Éloyes",
    "Embrun",
    "Émerainville - Pontault-Combault",
    "Enghien-les-Bains",
    "Ennevelin",
    "Entraigues-sur-la-Sorgue",
    "Entzheim Aéroport",
    "Epannes",
    "Épanvilliers",
    "Épernay",
    "Épernon",
    "Epfig",
    "Épierre - Saint-Léger",
    "Épinal",
    "Épinay - Villetaneuse",
    "Épinay - Villetaneuse",
    "Épinay-sur-Orge",
    "Épinay-sur-Orge",
    "Épinay-sur-Seine",
    "Épinay-sur-Seine",
    "Épluches",
    "Épône - Mézières",
    "Épouville",
    "Éragny - Neuville",
    "Erdre-Active",
    "Ermont - Eaubonne",
    "Ermont - Eaubonne",
    "Ermont Halte",
    "Err",
    "Erstein",
    "Esbly",
    "Escalquens",
    "Escaudœuvres",
    "Esches",
    "Espéraza",
    "Esquelbecq",
    "Essonnes Robinson",
    "Estavar",
    "Estrées-Saint-Denis",
    "Estressin",
    "Esvres sur Indre",
    "Étain",
    "Étainhus - Saint-Romain",
    "Étalans",
    "Étampes",
    "Étang-sur-Arroux",
    "Étaples - Le Touquet",
    "Étigny - Véron",
    "Étival-Clairefontaine",
    "Étréchy",
    "Étriché - Châteauneuf",
    "Eu",
    "Eu-la-Mouillette",
    "Eurville",
    "Évaux-les-Bains",
    "Évian-les-Bains",
    "Évreux Normandie",
    "Évron",
    "Évry Val de Seine",
    "Évry-Courcouronnes",
    "Évry-Courcouronnes",
    "Exideuil",
    "Eygurande - Merlines",
    "Eymoutiers Vassivière",
    "Èze",
    "Farbus",
    "Farébersviller",
    "Faremoutiers - Pommeuse",
    "Farschviller",
    "Faubourg d'Orléans",
    "Faulquemont",
    "Fécamp",
    "Fegersheim - Lipsheim",
    "Fellering",
    "Felletin",
    "Fenouillet - Saint-Alban",
    "Fépin",
    "Ferrières - Fontenay",
    "Feuquerolles",
    "Feuquières - Broquiers",
    "Feuquières - Fressenneville",
    "Feurs",
    "Feyzin",
    "Figeac",
    "Firminy",
    "Fismes",
    "Flaujac",
    "Flavy-le-Martel",
    "Flaxlanden",
    "Flers",
    "Fleurieux-sur-l'Arbresle",
    "Fleurville - Pont-de-Vaux",
    "Flez-Cuzy - Tannay",
    "Floirac (Lot)",
    "Foëcy",
    "Foix",
    "Folligny",
    "Fons - Saint-Mamert",
    "Fontainebleau - Avon",
    "Fontaine-Lavaganne",
    "Fontaine-le-Port",
    "Fontaines - Mercurey",
    "Fontaines-d'Ozillac",
    "Fontan - Saorge",
    "Fontenay-le-Fleury",
    "Fontenoy-sur-Moselle",
    "Fontpédrouse",
    "Font-Romeu-Odeillo-Via",
    "Forbach",
    "Formerie",
    "Fors",
    "Fos-sur-Mer",
    "Foucart - Alvimare",
    "Fouday",
    "Foug",
    "Fougeray - Langon",
    "Fougeré",
    "Fouilloy",
    "Fouquereuil",
    "Fourchambault",
    "Fourmies",
    "Fraisses - Unieux",
    "Franchet d'Esperey",
    "Francheville",
    "Franconville - Le Plessis-Bouchard",
    "Franois",
    "Frasne",
    "Freinville Sevran",
    "Fréjus",
    "Fréjus - Saint-Raphael Autotrain",
    "Frénouville - Cagny",
    "Frépillon",
    "Fresnoy-le-Grand",
    "Fréteval - Morée",
    "Fretin",
    "Frévin-Capelle",
    "Fromental",
    "Froncles",
    "Frontenex",
    "Frontignan",
    "Frouard",
    "Frynaudour",
    "Fumay",
    "Futuroscope",
    "Gadagne",
    "Gagny",
    "Gaillac",
    "Gaillon - Aubevoye",
    "Gallargues-le-Montueux",
    "Gallieni Cancéropôle",
    "Galuzot",
    "Gambsheim",
    "Gammal",
    "Gan",
    "Gandrange - Amnéville",
    "Gannat",
    "Gannes",
    "Gap",
    "Garancières - La Queue",
    "Garches - Marnes-la-Coquette",
    "Garchizy",
    "Gardanne",
    "Gardonne",
    "Gargan",
    "Gargenville",
    "Garges - Sarcelles",
    "Gauriaguet",
    "Gazeran",
    "Gazinet Cestas",
    "Geispolsheim",
    "Gemeaux",
    "Génelard",
    "Générac",
    "Genlis",
    "Gennevilliers",
    "Génolhac",
    "Germaine",
    "Gertwiller",
    "Gerzat",
    "Gestel",
    "Gevrey-Chambertin",
    "Gien",
    "Gièvres",
    "Gignac - Cressensac",
    "Gilles-Guainville",
    "Gilley",
    "Gilly-sur-Loire",
    "Gimont Cahuzac",
    "Gironde-sur-Dropt",
    "Gisors",
    "Givet",
    "Givors",
    "Givors Canal",
    "Glos - Montfort",
    "Golfe Juan Vallauris",
    "Golfech",
    "Goncelin",
    "Gonfaron",
    "Gorges",
    "Gourdon",
    "Gourland",
    "Gournay - Ferrières",
    "Goussainville",
    "Gouttières",
    "Goxwiller",
    "Graffenstaden",
    "Graffenwald",
    "Gragnague",
    "Gramat",
    "Grand Bourg",
    "Grand'Combe-Châteleu",
    "Grande-Synthe",
    "Grand-Pont-Preuilly",
    "Grandvillars",
    "Grandvilliers",
    "Granville",
    "Grasse",
    "Gravelines",
    "Gravigny Balizy",
    "Grenoble",
    "Grenoble Universités - Gières",
    "Gresswiller",
    "Grésy-sur-Aix",
    "Grésy-sur-Isère",
    "Gretz-Armainvilliers",
    "Grez-Gaudechart",
    "Grigny Centre",
    "Grigny le Sablon",
    "Grisolles",
    "Groisy - Thorens - La Caille",
    "Gros Noyer Saint-Prix",
    "Groslay",
    "Gudmont",
    "Guérard - La Celle-sur-Morin",
    "Guéret",
    "Guéthary",
    "Guichen - Bourg-des-Comptes",
    "Guignicourt",
    "Guillerval",
    "Guimiliau",
    "Guingamp",
    "Gujan-Mestras",
    "Gundershoffen",
    "Gunsbach - Griesbach",
    "Habsheim",
    "Hachette",
    "Hagondange",
    "Haguenau",
    "Halsou - Larressore",
    "Halte de Fontanil – Lycée de Drap",
    "Haluchère Batignolles",
    "Ham",
    "Ham-en-Artois",
    "Hangest-sur-Somme",
    "Harfleur",
    "Harfleur Halte",
    "Hargicourt - Pierrepont",
    "Hasenrain",
    "Hatrize",
    "Haubourdin",
    "Haussmann Saint-Lazare",
    "Haute Picardie TGV",
    "Hautmont",
    "Hayange",
    "Haybes",
    "Hazebrouck",
    "Heiligenberg - Mollkirch",
    "Heilles - Mouchy",
    "Heilly",
    "Hellemmes",
    "Hendaye",
    "Hénin-Beaumont",
    "Hennebont",
    "Herbitzheim",
    "Herblay",
    "Herchies",
    "Héricourt",
    "Héricy",
    "Hermes - Berthecourt",
    "Herny",
    "Herrlisheim",
    "Herrlisheim-près-Colmar",
    "Hesdigneul-lès-Boulogne",
    "Hesdin",
    "Hettange-Grande",
    "Hippodrome-de-la-côte-d'azur",
    "Hirson",
    "Hirson Écoles",
    "Hochfelden",
    "Hoelschloch",
    "Hoenheim Tram",
    "Hoerdt",
    "Hoffen",
    "Hombourg-Haut",
    "Homécourt",
    "Houdan",
    "Houdemont",
    "Houilles - Carrières-sur-Seine",
    "Houlgate",
    "Hundling",
    "Hunspach",
    "Huriel",
    "Hyères",
    "Hymont - Mattaincourt",
    "Igney",
    "Igney - Avricourt",
    "Igny",
    "Ille-sur-Têt",
    "Illfurth",
    "Illiers-Combray",
    "Imphy",
    "Ingersheim Cité Scolaire",
    "Ingrandes sur Vienne",
    "Ingrandes-Le Fresne-sur-Loire",
    "Ingwiller",
    "Invalides",
    "Irigny Yvours",
    "Isbergues",
    "Isles - Armentières - Congis",
    "Issé",
    "Issoire",
    "Issou - Porcheville",
    "Issoudun",
    "Is-sur-Tille",
    "Issy Val de Seine",
    "Issy-les-Moulineaux",
    "Istres",
    "Iteuil",
    "Itxassou",
    "Ivry-sur-Seine",
    "Iwuy",
    "Jacques Monod la Demi-Lieue",
    "Janzé",
    "Jarnac",
    "Jarrie - Vizille",
    "Jarville-la-Malgrange",
    "Jassonneix",
    "Jatxou",
    "Jaunay-Clan",
    "Jaux",
    "Javel",
    "Jeumont",
    "Jœuf",
    "Joigny",
    "Joigny-sur-Meuse",
    "Joinville",
    "Joncet",
    "Joncherey",
    "Jonchery-sur-Vesle",
    "Jonquières et Saint-Vincent",
    "Jonzac",
    "Joué-lès-Tours",
    "Jouy",
    "Jouy-en-Josas",
    "Juan les Pins",
    "Jussy",
    "Juvisy-sur-Orge",
    "Juziers",
    "Kalhausen",
    "Ker Lann",
    "Kerhostin",
    "Kerhuon",
    "Keskastel",
    "Kilstett",
    "Koenigsmacker",
    "Kogenheim",
    "Krimmeri Meinau",
    "Kruth",
    "Kurtzenhouse",
    "La Bachellerie",
    "La Barasse",
    "La Barre Ormesson",
    "La Basse Indre - Saint-Herblain",
    "La Bassée - Violaines",
    "La Bastide - Saint-Laurent-les-Bains",
    "La Baule Les Pins",
    "La Baule-Escoublac",
    "La Bernerie-en-Retz",
    "La Beuvrière",
    "La Bohalle",
    "La Boisse",
    "La Bonneville-sur-Iton",
    "La Borne Blanche",
    "La Bouble",
    "La Bourboule",
    "La Bouteille",
    "La Bridoire",
    "La Brigue",
    "La Brillanne - Oraison",
    "La Brohinière",
    "La Cave",
    "La Celle-Saint-Cloud",
    "La Chaize-le-Vicomte",
    "La Chapelle - Aulnay",
    "La Chapelle-Saint-Mesmin",
    "La Chapelle-sur-Erdre",
    "La Chapelle-sur-Loire",
    "La Charité-sur-Loire",
    "La Chaumusse - Fort-du-Plasne",
    "La Chaussée-Saint-Victor",
    "La Ciotat - Ceyreste",
    "La Clayette - Baudemont",
    "La Coquille",
    "La Courneuve - Aubervilliers",
    "La Couronne - Charente",
    "La Couronne Carro",
    "La Crau",
    "La Crèche",
    "La Croix de Méan",
    "La Défense",
    "La Défense",
    "La Douzillère",
    "La Faloise",
    "La Fère",
    "La Ferrière",
    "La Ferté-Alais",
    "La Ferté-Bernard",
    "La Ferté-Imbault",
    "La Ferté-Milon",
    "La Ferté-Saint-Aubin",
    "La Ferté-sous-Jouarre",
    "La Fontaine",
    "La Forest-Landerneau",
    "La Fouillouse",
    "La Frayère",
    "La Fresnais",
    "La Frette - Montigny",
    "La Garde",
    "La Garenne-Colombes",
    "La Gorp",
    "La Gouesnière - Cancale",
    "La Grand-Combe",
    "La Grande-Paroisse",
    "La Grave d'Ambarès",
    "La Guerche-sur-l'Aubois",
    "La Guierche",
    "La Haie-Fouassière",
    "La Hisse",
    "La Hume",
    "La Hutte Coulombiers",
    "La Jarrie",
    "La Jonchère-Saint-Maurice",
    "La Joux",
    "La Levade",
    "La Loupe",
    "La Madeleine",
    "La Marche",
    "La Méaugon",
    "La Meilleraie (Vendée)",
    "La Membrolle-sur-Choisille",
    "La Ménitré",
    "La Meyze",
    "La Miouze - Rochefort",
    "La Mothe-Achard",
    "La Mothe-Saint-Héray",
    "La Neuville-sous-Laon",
    "La Norville - Saint-Germain-lès-Arpajon",
    "La Pauline Hyères",
    "La Penne-sur-Huveaune",
    "La Plaine Stade de France - Saint-Denis",
    "La Pomme",
    "La Porcherie",
    "La Possonnière",
    "La Poterie",
    "La Redonne Ensuès",
    "La Réole",
    "La Ricamarie",
    "La Rivière de Mansac",
    "La Rivière-Drugeon",
    "La Roche-en-Brenil",
    "La Rochefoucauld",
    "La Rochelle",
    "La Rochelle Porte Dauphine",
    "La Roche-Maurice",
    "La Roche-sur-Foron",
    "La Roche-sur-Yon",
    "La Seyne - Six-Fours",
    "La Souterraine",
    "La Suze",
    "La Taye",
    "La Teste-de-Buch",
    "La Tour-de-Salvagny",
    "La Tour-du-Pin",
    "La Tricherie",
    "La Trinité Victor",
    "La Valbonne",
    "La Vavrette-Tossiat",
    "La Verpillière",
    "La Verrière",
    "La Ville Gozet",
    "La Ville-Dieu-du-Temple",
    "La Villette Saint-Prest",
    "La Wantzenau",
    "Labarre",
    "Labarthe-Inard",
    "L'Abbaye",
    "Labège Innopole",
    "Labège Village",
    "Labenne",
    "Labergement-Sainte-Marie",
    "Laboissière - Le Déluge",
    "Labouheyre",
    "Labruguière",
    "Lacapelle-Viescamp",
    "Lacelle",
    "Lachaud Curmilhac",
    "Lacourtensourt",
    "Lafarge",
    "Lagny - Thorigny",
    "Laguépie",
    "Laifour",
    "L'Aigle",
    "Laigné - Saint-Gervais",
    "Laigneville",
    "L'Aiguille",
    "Laillé",
    "Laissac",
    "Laissey",
    "Lalande Église",
    "Lalbenque - Fontanes",
    "Lalinde",
    "Lamagistère",
    "Lamanon",
    "Lamativie",
    "Lamballe",
    "Lamonzie-Saint-Martin",
    "Lamothe-Landerron",
    "Lamothe-Montravel",
    "Lamotte-Beuvron",
    "Lamure-sur-Azergues",
    "Lancerf",
    "Lancey",
    "Landas",
    "Landaul - Mendon",
    "Landébia",
    "Landerneau",
    "Landévant",
    "Landivisiau",
    "Landrecies",
    "Landry",
    "Laneuveville-devant-Nancy",
    "Langeac",
    "Langeais",
    "Langogne",
    "Langon",
    "Langres",
    "Lannemezan",
    "Lannion",
    "Lantenay",
    "Laon",
    "Lapalisse-St-Prix",
    "Lapeyrouse",
    "Laqueuille",
    "Laragne-Montéglin",
    "L'Arbresle",
    "Larche",
    "Lardenne",
    "Lardy",
    "L'Argentière Les Écrins",
    "L'Ariane La Trinité",
    "Laroche - Migennes",
    "Laroquebrou",
    "Laroque-Timbaut",
    "Lathus-Saint-Rémy",
    "Latour-de-Carol - Enveitg",
    "Lauterbourg",
    "Laval",
    "Laval-de-Cère",
    "Lavaufranche",
    "Lavaur",
    "Lavaveix-les-Mines",
    "Laveline-devant-Bruyères",
    "Lavilletertre",
    "Lavoûte-sur-Loire",
    "Le Blanc-Mesnil",
    "Le Bosquet",
    "Le Bourget",
    "Le Bourget",
    "Le Bousquet-d'Orb",
    "Le Bras de Fer",
    "Le Breuil-sur-Couze",
    "Le Bruel",
    "Le Buet",
    "Le Bugue",
    "Le Buisson-de-Cadouin",
    "Le Burg",
    "Le Cailar",
    "Le Canet",
    "Le Cateau-Cambrésis",
    "Le Cellier",
    "Le Cendre - Orcet",
    "Le Chambon-Feugerolles",
    "Le Chénay Gagny",
    "Le Coteau",
    "Le Coudray-Montceaux",
    "Le Creusot",
    "Le Creusot - Montceau-les-Mines TGV",
    "Le Croisic",
    "Le Dorat",
    "Le Dramont",
    "Le Fauga",
    "Le Genest-Saint-Isle",
    "Le Grand Jardin",
    "Le Grand-Lemps",
    "Le Grau-du-Roi",
    "Le Haut Banc",
    "Le Havre",
    "Le Havre Graville",
    "Le Lioran",
    "Le Locle-Col-des-Roches",
    "Le Luc - Le Cannet",
    "Le Mans",
    "Le Mans hôpital-université",
    "Le Mée-sur-Seine",
    "Le Méridien La Ferrière",
    "Le Merlerault",
    "Le Meux - La Croix-Saint-Ouen",
    "Le Molay-Littry",
    "Le Monastier-Pin-Moriès",
    "Le Pallet",
    "Le Pas",
    "Le Péage-de-Roussillon",
    "Le Pénity",
    "Le Perray-en-Yvelines",
    "Le Plessis Chenet",
    "Le Plessis-Belleville",
    "Le Poirier Université",
    "Le Pont-de-Beauvoisin",
    "Le Pont-de-Claix",
    "Le Pouliguen",
    "Le Puy-en-Velay",
    "Le Quesnoy",
    "Le Raincy - Villemomble - Montfermeil",
    "Le Rouget",
    "Le Saut-du-Loup",
    "Le Soler",
    "Le Stade",
    "Le Teich",
    "Le Teil",
    "Le Theil - La Rouge",
    "Le Theil-de-Bretagne",
    "Le Thor",
    "Le Toec",
    "Le Trayas",
    "Le Tréport - Mers-les-Bains",
    "Le Val d'Or",
    "Le Vauriat",
    "Le Verdon-sur-Mer",
    "Le Vernet d'Ariège",
    "Le Vert de Maisons",
    "Le Vieux Briollay",
    "Leforest",
    "Lens",
    "Lentilly",
    "Lentilly Charpenay",
    "Lépanges",
    "Lépin-le-Lac - La Bauche",
    "Lérouville",
    "Les Abrets - Fitilieu",
    "Les Ancizes-St-Georges",
    "Les Arcs - Draguignan",
    "Les Ardoines",
    "Les Aubrais",
    "Les Bardys",
    "Les Bons Pères",
    "Les Bossons",
    "Les Boullereaux Champigny",
    "Les Cabannes",
    "Les Cabrils",
    "Les Cauquillous",
    "Les Champs-Forts",
    "Les Clairières de Verneuil",
    "Les Clouzeaux",
    "Les Coquetiers",
    "Les Deux Jumeaux",
    "Les Échets",
    "Les Églisottes-et-Chalaures",
    "Les Essarts-le-Roi",
    "Les Eyzies-de-Tayac-Sireuil",
    "Les Flachères",
    "Les Fontinettes",
    "Les Grésillons",
    "Les Houches",
    "Les Islettes",
    "Les Lacs",
    "Les Laumes Alésia",
    "Les Longevilles-Rochejean",
    "Les Mais",
    "Les Martres-de-Veyre",
    "Les Mazes le Crès",
    "Les Moussoux",
    "Les Moutiers-en-Retz",
    "Les Mureaux",
    "Les Noues",
    "Les Ormes",
    "Les Pavillons-sous-Bois",
    "Les Pélerins",
    "Les Perrières",
    "Les Portes de Saint-Cyr T13",
    "Les Praz de Chamonix",
    "Les Quatre Roues",
    "Les Quatre-Routes-du-Lot",
    "Les Ramassiers",
    "Les Rosiers-sur-Loire",
    "Les Sables Blancs",
    "Les Sables-d'Olonne",
    "Les Salelles",
    "Les Saules",
    "Les Tines",
    "Les Trillers",
    "Les Vallées",
    "Les Versannes",
    "Les Yvris Noisy-le-Grand",
    "L'Escarène",
    "Lesparre-Médoc",
    "Lesquin",
    "Lesseux - Frapelle",
    "L'Estaque",
    "Lestelle",
    "L'Étang-la-Ville",
    "L'Étang-la-Ville - Les Sablons",
    "Létrade",
    "Leucate La Franqui",
    "Leval",
    "Lexos",
    "Lezennes",
    "Lézignan-Corbières",
    "Lezoux",
    "L'Herbergement - Les Brouzils",
    "L'Hermitage - Mordelles",
    "L'Hôpital-du-Grosbois",
    "L'Hospitalet-près-l'Andorre",
    "Liancourt - Rantigny",
    "Liancourt-Saint-Pierre",
    "Liart",
    "Libercourt",
    "Libourne",
    "Liernais",
    "Liesle",
    "Lieusaint - Moissy",
    "Liévin",
    "Lignerolles",
    "Ligugé",
    "Lille CHR",
    "Lille Europe",
    "Lille Flandres",
    "Lille Porte de Douai",
    "Lillers",
    "Limay",
    "Limeray",
    "Limersheim",
    "Limeyrat",
    "Limoges Bénédictins",
    "Limoges Montjovis",
    "Limoux",
    "Limoux Flassian",
    "Lingolsheim",
    "Lisière Pereire T13",
    "Lisieux",
    "L'Isle-Adam - Parmain",
    "L'Isle-d'Abeau",
    "L'Isle-Jourdain",
    "L'Isle-sur-la-Sorgue - Fontaine-de-Vaucluse",
    "L'Isle-sur-le-Doubs",
    "Lisle-sur-Tarn",
    "Lison",
    "L'Isthme",
    "Liverdun",
    "Livron-sur-Drôme",
    "Livry-sur-Seine",
    "Lizy-sur-Ourcq",
    "Loches",
    "Logelbach",
    "Loison-sous-Lens",
    "Loivre",
    "Longages - Noé",
    "Longecourt-en-Plaine",
    "Longjumeau",
    "Longpont",
    "Longpré-les-Corps-Saints",
    "Longroy - Gamaches",
    "Longueau",
    "Longueil-Annel",
    "Longueil-Sainte-Marie",
    "Longuerue - Vieux-Manoir",
    "Longueville",
    "Longueville-sur-Scie",
    "Longuyon",
    "Longwy",
    "Lons-le-Saunier",
    "Loos lez Lille",
    "Loos-en-Gohelle",
    "Loreux",
    "Lorient Bretagne Sud",
    "Loriol-sur-Drôme",
    "Lorraine TGV",
    "Lothiers",
    "Louhans",
    "Louhossoa",
    "Loulay",
    "Lourches",
    "Lourdes",
    "Louroux-de-Bouble",
    "Louveciennes",
    "Louverné",
    "Louvres",
    "Louvroil",
    "Lozanne",
    "Luant",
    "Lubersac",
    "Luc",
    "Lucé",
    "Luc-en-Diois",
    "Luc-la-Primaube",
    "Luçon",
    "Lucy-sur-Cure - Bessy",
    "Ludon-Médoc",
    "Ludres",
    "Lumes",
    "Lunas",
    "Lunel",
    "Lunel-Viel",
    "Lunery",
    "Lunéville",
    "Lurbe-Saint-Christau",
    "Lure",
    "Lusignan",
    "Lus-la-Croix-Haute",
    "Lussac-les-Châteaux",
    "Luttenbach-près-Munster",
    "Lutterbach",
    "Lutterbach",
    "Lutzelbourg",
    "Lutzelhouse",
    "Luxé",
    "Luxeuil-les-Bains",
    "Luzarches",
    "Luzenac - Garanou",
    "Luzy",
    "Lycée Henri Sellier",
    "Lyon Gorge de Loup",
    "Lyon Jean Macé",
    "Lyon Part Dieu",
    "Lyon Perrache",
    "Lyon Saint-Exupéry TGV",
    "Lyon Saint-Paul",
    "Lyon Vaise",
    "Macau",
    "Machecoul",
    "Machilly",
    "Mâcon",
    "Mâcon Loché TGV",
    "Magalas",
    "Magenta",
    "Magland",
    "Magnac - Vicq",
    "Magnette",
    "Magneux - Courlandon",
    "Magny - Blandainville",
    "Maillé",
    "Mailly-la-Ville",
    "Maintenon",
    "Maison-Dieu (Yonne)",
    "Maisons-Alfort - Alfortville",
    "Maisons-Laffitte",
    "Maisse",
    "Maizières-lès-Metz",
    "Mâlain",
    "Malansac",
    "Malaunay - Le Houlme",
    "Malause",
    "Malesherbes",
    "Malling",
    "Mamirolle",
    "Mandelieu-la-Napoule",
    "Manduel - Redessan",
    "Manlay",
    "Manosque - Gréoux-les-Bains",
    "Mantes Station",
    "Mantes-la-Jolie",
    "Marans",
    "Marbache",
    "Marcelcave",
    "Marcheprime",
    "Marchezais - Broué",
    "Mareil-Marly",
    "Mareil-Marly",
    "Mareil-sur-Mauldre",
    "Maresquel-Ecquemicourt",
    "Mareuil-sur-Ourcq",
    "Margaux",
    "Margival",
    "Marienthal",
    "Marignier",
    "Marigny",
    "Marle sur Serre",
    "Marles-en-Brie",
    "Marlieux - Châtillon",
    "Marly-le-Roi",
    "Marmagne",
    "Marmagne sous Creusot",
    "Marmande",
    "Marne-la-Vallée Chessy",
    "Maroeuil",
    "Marolles-en-Hurepoix",
    "Maromme",
    "Marquette",
    "Marquillies",
    "Marquise - Rinxent",
    "Marquixanes",
    "Marsac",
    "Marsac-sur-l'Isle",
    "Marseillan Plage",
    "Marseille Blancarde",
    "Marseille Saint-Charles",
    "Marseille-en-Beauvaisis",
    "Marssac-sur-Tarn",
    "Martigné-Ferchaud",
    "Martigues",
    "Martres-Tolosane",
    "Marvejols",
    "Massérac",
    "Masseret",
    "Massiac - Blesle",
    "Massy - Palaiseau",
    "Massy - Verrières",
    "Massy TGV",
    "Matzenheim",
    "Maubeuge",
    "Maule",
    "Maurecourt",
    "Maurois",
    "Maurs",
    "Mauves-sur-Loire",
    "Mauzac-et-Grand-Castang",
    "Mauzens-et-Miremont",
    "Mauzé-sur-le-Mignon",
    "Mayet",
    "Mazamet",
    "Mazingarbe",
    "Meaux",
    "Mehun-sur-Yèvre",
    "Melun",
    "Menars",
    "Mende",
    "Ménerville",
    "Ménil Flin",
    "Mennecy",
    "Mennessis",
    "Mennetou-sur-Cher",
    "Menton",
    "Menton Garavan",
    "Mer",
    "Mérens-les-Vals",
    "Mérenvielle",
    "Méricourt - Ribemont",
    "Mériel",
    "Mérignac Arlac",
    "Méroux",
    "Merrey",
    "Mertzwiller",
    "Méru",
    "Mervans",
    "Merxheim",
    "Méry-sur-Oise",
    "Messac - Guipry",
    "Messein",
    "Mesves - Bulcy",
    "Mesvres",
    "Metz",
    "Metz Nord",
    "Metzeral",
    "Meudon",
    "Meudon Val Fleury",
    "Meulan - Hardricourt",
    "Meung-sur-Loire",
    "Meurchin",
    "Meursault",
    "Meuse TGV",
    "Meximieux - Pérouges",
    "Meymac",
    "Meyrargues",
    "Mézériat",
    "Mézidon-Canon",
    "Mignaloux - Nouaillé",
    "Milhac-d'Auberoche",
    "Milhaud",
    "Millas",
    "Millau",
    "Milly-sur-Thérain",
    "Miniac-Morvan",
    "Mionnay",
    "Miramas",
    "Miraumont",
    "Mirecourt",
    "Miribel",
    "Miserey-Salines",
    "Mitry - Claye",
    "Modane",
    "Mohon",
    "Moirans",
    "Moirans La Galifette",
    "Moissac",
    "Moliens",
    "Molières-sur-Cèze",
    "Molinges",
    "Molsheim",
    "Mommenheim",
    "Monestier-de-Clermont",
    "Monéteau - Gurgy",
    "Monistrol-d'Allier",
    "Monnaie",
    "Monnerville",
    "Monsempron-Libos",
    "Mont de Terre",
    "Montaignac-Saint-Hippolyte",
    "Montaigu",
    "Montaigut-le-Blanc",
    "Montargis",
    "Montastruc-la-Conseillère",
    "Montataire",
    "Montauban Ville Bourbon",
    "Montauban-de-Bretagne",
    "Montaudran",
    "Montaut Bétharram",
    "Montbard",
    "Montbarrey",
    "Montbartier",
    "Montbazon",
    "Montbéliard",
    "Montbeugny",
    "Montbizot",
    "Montbré",
    "Montbrison",
    "Montcaret",
    "Montceau-les-Mines",
    "Montchanin",
    "Mont-Dauphin - Guillestre",
    "Mont-de-Marsan",
    "Montdidier",
    "Mont-Dore",
    "Monte-Carlo Country Club",
    "Monteils",
    "Montélimar",
    "Montendre",
    "Montereau",
    "Montérolier - Buchy",
    "Montescourt-Lizerolles",
    "Monteux",
    "Montfavet",
    "Montferrand - Thoraise",
    "Montfort-l'Amaury - Méré",
    "Montfort-le-Gesnois",
    "Montfort-sur-Meu",
    "Montgeron - Crosne",
    "Montgeroult - Courcelles",
    "Monthermé",
    "Montigny - Beauchamp",
    "Montigny-en-Ostrevent",
    "Montigny-sur-Loing",
    "Montivilliers",
    "Montlaur",
    "Mont-Louis - La Cabanasse",
    "Montlouis-sur-Loire",
    "Montluçon",
    "Montluçon Rimard",
    "Montluel",
    "Montmédy",
    "Montmélian",
    "Montmoreau",
    "Montmorillon",
    "Montoir-de-Bretagne",
    "Montpaon",
    "Montpellier Saint-Roch",
    "Montpellier Sud de France",
    "Montpon-Ménestérol",
    "Montrabé",
    "Montréjeau - Gourdan-Polignan",
    "Montreuil",
    "Montreuil sur Mer",
    "Montreuil-Bellay",
    "Montreuil-sur-Ille",
    "Montreuil-sur-Thérain",
    "Montreux-Vieux",
    "Montrichard",
    "Montroc le Planet",
    "Montrond-les-Bains",
    "Montry - Condé",
    "Monts",
    "Montsoult - Maffliers",
    "Mont-sur-Meurthe",
    "Montsûrs",
    "Montville",
    "Moosch",
    "Morannes",
    "Morbier",
    "Morcenx",
    "Moret - Veneux-les-Sablons",
    "Moreuil",
    "Morez",
    "Morgny-la-Pommeraye",
    "Morhange",
    "Morières-lès-Avignon",
    "Morlaix",
    "Mormant",
    "Morre",
    "Mortcerf",
    "Morteau",
    "Morvillars",
    "Mothern",
    "Motteville",
    "Mouans-Sartoux",
    "Mouchard",
    "Moulin Galant",
    "Moulins sur Allier",
    "Moulis - Listrac",
    "Moult - Argences",
    "Mourmelon-le-Petit",
    "Mouroux",
    "Moustéru",
    "Moûtiers - Salins - Brides-les-Bains",
    "Mouy - Bury",
    "Moyeuvre-Grande",
    "Muhlbach-sur-Munster",
    "Muizon",
    "Mulhouse",
    "Mulhouse Dornach",
    "Mulhouse Dornach",
    "Mulhouse Musées",
    "Mulhouse Zu Rhein",
    "Mullerhof",
    "Munchhausen",
    "Mundolsheim",
    "Munster",
    "Munster Badischhof",
    "Murat",
    "Muret",
    "Musée d'Orsay",
    "Mussidan",
    "Mutzig",
    "Naintré",
    "Najac",
    "Namps - Quevauvillers",
    "Nançois - Tronville",
    "Nancy",
    "Nangis",
    "Nanterre Université",
    "Nantes",
    "Nanteuil - Saâcy",
    "Nanteuil-le-Haudouin",
    "Nantiat",
    "Narbonne",
    "Naucelle",
    "Naussac",
    "Neau",
    "Négrondes",
    "Nemours - Saint-Pierre",
    "Nérondes",
    "Nerpuy",
    "Nesle",
    "Neufchâteau",
    "Neufchâtel-Hardelot",
    "Neuillé-Pont-Pierre",
    "Neuilly - Porte Maillot",
    "Neuilly - Porte Maillot",
    "Neuilly-lès-Dijon",
    "Neussargues",
    "Neuves-Maisons",
    "Neuvic",
    "Neuville Université",
    "Neuville-sur-Sarthe",
    "Neuvy-Pailloux",
    "Nevers",
    "Nevers Le Banlay",
    "Nexon",
    "Nézel - Aulnay",
    "Nice",
    "Nice Pont Michel",
    "Nice Riquier",
    "Nice Saint Roch",
    "Nice Saint-Augustin",
    "Niederbronn-les-Bains",
    "Nieppe",
    "Nieul",
    "Nîmes",
    "Nîmes Pont du Gard",
    "Niolon",
    "Niort",
    "Nissan",
    "Niversac",
    "Nœux-les-Mines",
    "Nogent - Le Perreux",
    "Nogent-l'Artaud - Charly",
    "Nogent-le-Rotrou",
    "Nogent-sur-Seine",
    "Nogent-sur-Vernisson",
    "Nointel - Mours",
    "Noirétable",
    "Noirterre",
    "Noisy-le-Roi",
    "Noisy-le-Roi",
    "Noisy-le-Sec",
    "Noizay",
    "Nomain",
    "Nonancourt",
    "Nonant-le-Pin",
    "Nortkerque",
    "Nort-sur-Erdre",
    "Notre-Dame de Briançon",
    "Notre-Dame-d'Oé",
    "Nouan-le-Fuzelier",
    "Nouvion-sur-Meuse",
    "Nouzonville",
    "Novéant-sur-Moselle",
    "Novillars",
    "Noyal - Acigné",
    "Noyelles-sur-Mer",
    "Noyen-sur-Sarthe",
    "Noyon",
    "Nozières - Brignon",
    "Nuces",
    "Nuits sous Ravières",
    "Nuits-Saint-Georges",
    "Nurieux-Volognat",
    "Nyer",
    "Obermodern-Zutzendorf",
    "Obernai",
    "Objat",
    "Oderen",
    "Oermingen",
    "Ogeu-les-Bains",
    "Oissel",
    "Olette - Canaveilles",
    "Ollioules - Sanary-sur-Mer",
    "Olonne-sur-Mer",
    "Oloron-Sainte-Marie",
    "Ondres",
    "Onville",
    "Onzain - Chaumont-sur-Loire",
    "Orange",
    "Orangis Bois de l'Épine",
    "Orchamps",
    "Orchies",
    "Orgerus - Béhoust",
    "Orgon",
    "Origny-en-Thiérache",
    "Orléans",
    "Orly Ville",
    "Ormoy-Villers",
    "Orry-la-Ville - Coye",
    "Ors",
    "Orthez",
    "Osny",
    "Osséja",
    "Ossès - Saint-Martin-d'Arrossa",
    "Ossun",
    "Ostricourt",
    "Oudon",
    "Ouges",
    "Oullins",
    "Ourscamps",
    "Oyonnax",
    "Ozoir-la-Ferrière",
    "Pagny-le-Château",
    "Pagny-sur-Meuse",
    "Pagny-sur-Moselle",
    "Paimpol",
    "Palinges",
    "Pamiers",
    "Pamproux",
    "Pantin",
    "Paradis",
    "Paraire",
    "Paray-le-Monial",
    "Parc des Expositions",
    "Parempuyre",
    "Parent - Coudes - Champeix",
    "Paris Austerlitz",
    "Paris Austerlitz",
    "Paris Bercy Bourgogne - Pays d'Auvergne",
    "Paris Est",
    "Paris Gare de Lyon",
    "Paris Gare de Lyon",
    "Paris Gare du Nord",
    "Paris Gare du Nord",
    "Paris Gare du Nord",
    "Paris Gare du Nord",
    "Paris Montparnasse",
    "Paris Montparnasse",
    "Paris Saint-Lazare",
    "Parsac - Gouzon",
    "Pas des Lanciers",
    "Pau",
    "Pauillac",
    "Paulhaguet",
    "Pavilly",
    "Peille",
    "Peillon Sainte-Thècle",
    "Peltre",
    "Penhoët",
    "Penne-d'Agenais",
    "Penthièvre",
    "Péreire - Levallois",
    "Pérenchies",
    "Périgueux",
    "Périgueux Saint-Georges",
    "Pernes - Camblain",
    "Pérols-sur-Vézère",
    "Perpignan",
    "Perrignier",
    "Pers",
    "Persan - Beaumont",
    "Pertuis",
    "Pessac",
    "Pessac Alouette",
    "Petit Coeur la Léchère les Bains",
    "Petit Jouy - Les Loges",
    "Petit Vaux",
    "Petit-Croix",
    "Pexiora",
    "Peyrehorade",
    "Peyrilhac - Saint-Jouvent",
    "Pezou",
    "Phalempin",
    "Pibrac",
    "Picon Busserine",
    "Picquigny",
    "Pierre-Bénite",
    "Pierre-Buffière",
    "Pierrefitte - Stains",
    "Pierrefitte - Stains",
    "Pierrelatte",
    "Pierrelaye",
    "Pierreville",
    "Pierroton",
    "Pignans",
    "Pihen-lès-Guînes",
    "Pins-Justaret",
    "Plaisir - Grignon",
    "Plaisir - Les Clayes",
    "Plancoët",
    "Planès",
    "Pléchâtel",
    "Plénée-Jugon",
    "Plerguer",
    "Plestan",
    "Pleudihen-sur-Rance",
    "Pleyber-Christ",
    "Plouaret Trégor",
    "Plougonver",
    "Plouharnel - Carnac",
    "Plouigneau",
    "Plounérin",
    "Plouvara - Plerneuf",
    "Podensac",
    "Pointe de Grave",
    "Poissy",
    "Poitiers",
    "Poix-de-Picardie",
    "Poix-Terron",
    "Poliénas",
    "Poligny",
    "Polliat",
    "Polminhac",
    "Pomas",
    "Pommevic",
    "Pompadour",
    "Pompey",
    "Pons",
    "Pont Cardinet",
    "Pont d'Ardres",
    "Pont de Bois",
    "Pont de Briques",
    "Pont de Dore",
    "Pont de la Deûle",
    "Pont de l'Alma",
    "Pont de Lignon",
    "Pont de Rungis Aéroport d'Orly",
    "Pont de Sallaumines",
    "Pont du Garigliano - Hôpital Européen",
    "Pont Petit",
    "Pont-à-Mousson",
    "Pontanevaux",
    "Pontarlier",
    "Pont-à-Vendin",
    "Pontchaillou",
    "Pontcharra - Saint-Forgeux",
    "Pontcharra sur Bréda",
    "Pontchâteau",
    "Pont-d'Ain",
    "Pont-de-Buis",
    "Pont-de-l'Arche",
    "Pont-de-Veyle",
    "Pont-du-Casse",
    "Pont-du-Château",
    "Pont-du-Château",
    "Pontgibaud",
    "Pontgouin",
    "Pont-Hébert",
    "Ponthierry - Pringy",
    "Pont-l'Évêque",
    "Pont-l'Évêque-sur-Oise",
    "Pont-Melvez",
    "Pontmort",
    "Pontoise",
    "Pontorson - Mont-Saint-Michel",
    "Pont-Remy",
    "Pontrieux",
    "Pontrieux Halte",
    "Pont-Sainte-Maxence",
    "Pont-Saint-Esprit",
    "Pont-Saint-Vincent",
    "Pont-sur-Yonne",
    "Porchefontaine",
    "Pornic",
    "Pornichet",
    "Port Boulet",
    "Porta",
    "Port-Brillet",
    "Port-de-Bouc",
    "Port-de-Piles",
    "Porte de Clichy",
    "Porté-Puymorens",
    "Portes-de-Vesoul",
    "Portet Saint-Simon",
    "Portets",
    "Port-la-Nouvelle",
    "Port-Sainte-Marie",
    "Port-Saint-Père - Saint-Mars",
    "Port-Vendres",
    "Port-Villez",
    "Pougny - Chancy",
    "Pougues-les-Eaux",
    "Pouilly-sur-Loire",
    "Poule",
    "Pouxeux",
    "Pouzauges",
    "Prades - Molitg-les-Bains",
    "Précy-sur-Oise",
    "Preignac",
    "Presles Courcelles",
    "Prigonrieux-La Force",
    "Prin-Deyrançon",
    "Pringy",
    "Prissé-la-Charrière",
    "Prouvy - Thiant",
    "Provenchères-sur-Fave",
    "Provins",
    "Prunay",
    "Pruniers-en-Sologne",
    "Puget-Ville",
    "Pulligny - Autrey",
    "Puteaux",
    "Puybrun",
    "Puyoô",
    "Quédillac",
    "Quesnoy-le-Montant",
    "Quesnoy-sur-Deûle",
    "Questembert",
    "Quiberon",
    "Quillan",
    "Quimper",
    "Quimperlé",
    "Quincieux",
    "Rabastens - Coufouleux",
    "Raedersheim",
    "Rai - Aube",
    "Raismes",
    "Rambouillet",
    "Ranchot",
    "Rang-du-Fliers - Verton - Berck",
    "Ranguin",
    "Ranspach",
    "Raon-l'Étape",
    "Rassuen",
    "Raves - Ban-de-Laveline",
    "Ravezies",
    "Razac-sur-l'Isle",
    "Réalville",
    "Réaumont - Saint-Cassien",
    "Recquignies",
    "Réding",
    "Redon",
    "Régny",
    "Reichshoffen",
    "Reignac-sur-Indre",
    "Reignier",
    "Reims",
    "Reims Maison Blanche",
    "Rémelfing",
    "Rémilly",
    "Remiremont",
    "Remise à Jorelle",
    "Remy",
    "Renescure",
    "Rennes",
    "Reterre",
    "Rethel",
    "Retiers",
    "Retournac",
    "Reuilly",
    "Revigny-sur-Ornain",
    "Revin",
    "Rezé Pont Rousseau",
    "Ria-Sirach",
    "Ribécourt",
    "Riedseltz",
    "Rieux - Angicourt",
    "Rilly-la-Montagne",
    "Riom - Châtel-Guyon",
    "Ris-Orangis",
    "Rivarennes",
    "Rive-de-Gier",
    "Rives",
    "Rivesaltes",
    "Rixheim",
    "Roanne",
    "Robiac",
    "Rocamadour - Padirac",
    "Rochefort",
    "Roche-lez-Beaupré",
    "Rochy-Condé",
    "Rodez",
    "Roeschwoog",
    "Rœux",
    "Rognac",
    "Roissy-en-Brie",
    "Rolleville",
    "Romanèche-Thorins",
    "Romans - Bourg-de-Péage",
    "Rombas - Clouange",
    "Romilly-la-Puthenaye",
    "Romilly-sur-Seine",
    "Romorantin Blanc Argent",
    "Ronchamp",
    "Ronchin",
    "Roppenheim",
    "Roquebrune-Cap-Martin",
    "Roquesérière - Buzet",
    "Rosa Parks",
    "Roscoff",
    "Rosheim",
    "Rosières",
    "Rosières-aux-Salines",
    "Rosny Bois Perrier",
    "Rosny-sous-Bois",
    "Rosny-sur-Seine",
    "Rosporden",
    "Rosult",
    "Rothau",
    "Roubaix",
    "Rouen Rive Droite",
    "Rouessé-Vassé",
    "Rouffach",
    "Rougemont Chanteloup",
    "Rouillé",
    "Roumazières-Loubert",
    "Rountzenheim",
    "Route de Launaguet",
    "Royan",
    "Royat - Chamalières",
    "Rozières-sur-Mouzon",
    "Rue",
    "Ruelle-sur-Touvre",
    "Ruffec",
    "Ruffey-lès-Echirey",
    "Rully",
    "Rumilly",
    "Ruminghem",
    "Rungis La Fraternelle",
    "Russ Hersbach",
    "Saales",
    "Sablé-sur-Sarthe",
    "Saillagouse",
    "Saillans",
    "Saillat - Chassenon",
    "Sain-Bel",
    "Saincaize-Meauce",
    "Sains-du-Nord",
    "Saint-Agnan",
    "Saint-Agne",
    "Saint-Aignan - Noyers",
    "Saint-Aigulin - La Roche-Chalais",
    "Saint-Amand-les-Eaux",
    "Saint-Amand-Longpré",
    "Saint-Amand-Montrond - Orval",
    "Saint-Amarin",
    "Saint-Ambroix",
    "Saint-Amour",
    "Saint-André-de-Corcy",
    "Saint-André-de-Cubzac",
    "Saint-André-le-Gaz",
    "Saint-André-lez-Lille",
    "Saint-Antoine",
    "Saint-Antoine-de-Breuilh",
    "Saint-Antoine-du-Rocher",
    "Saint-Armel",
    "Saint-Astier",
    "Saint-Aubin - Saint-Luperce",
    "Saint-Aubin-sur-Scie",
    "Saint-Aulaire",
    "Saint-Aunès",
    "Saint-Avold",
    "Saint-Avre - La Chambre",
    "Saint-Ay",
    "Saint-Béron - La Bridoire",
    "Saint-Blaise-la-Roche Poutay",
    "Saint-Bonnet-de-Rochefort",
    "Saint-Brès - Mudaison",
    "Saint-Brice-sur-Vienne",
    "Saint-Brieuc",
    "Saint-Césaire",
    "Saint-Chamas",
    "Saint-Chamond",
    "Saint-Chély-d'Apcher",
    "Saint-Chéron",
    "Saint-Christophe-Vallon",
    "Saint-Clair - Les Roches",
    "Saint-Claude",
    "Saint-Clément - Laronxe",
    "Saint-Cloud",
    "Saint-Cyprien",
    "Saint-Cyprien Arènes",
    "Saint-Cyr Les Lecques - La Cadière",
    "Saint-Cyr-en-Val La Source",
    "Saint-Cyr-l'École",
    "Saint-Dalmas de Tende",
    "Saint-Denis",
    "Saint-Denis-de-Pile",
    "Saint-Denis-des-Murs",
    "Saint-Denis-lès-Martel",
    "Saint-Dié-des-Vosges",
    "Saint-Dizier",
    "Sainte-Anne",
    "Sainte-Bazeille",
    "Sainte-Cécile-d'Andorge",
    "Sainte-Colombe",
    "Sainte-Colombe Septveilles",
    "Sainte-Eulalie - Carbon-Blanc",
    "Sainte-Foy-la-Grande",
    "Sainte-Gauburge",
    "Sainte-Geneviève-des-Bois",
    "Saint-Égrève Saint-Robert",
    "Sainte-Léocadie",
    "Sainte-Lizaigne",
    "Sainte-Marguerite",
    "Sainte-Marthe en Provence",
    "Sainte-Maure - Noyant",
    "Saint-Émilion",
    "Sainte-Pazanne",
    "Saint-Erme-Outre-et-Ramecourt",
    "Saintes",
    "Saint-Étienne Bellevue",
    "Saint-Étienne Carnot",
    "Saint-Étienne Châteaucreux",
    "Saint-Étienne La Terrasse",
    "Saint-Étienne Le Clapier",
    "Saint-Étienne-de-Montluc",
    "Saint-Étienne-du-Rouvray",
    "Saint-Fargeau",
    "Saint-Féliu-d'Avall",
    "Saint-Florentin - Vergigny",
    "Saint-Florent-sur-Cher",
    "Saint-Flour - Chaudes-Aigues",
    "Saint-Fons",
    "Saint-Gaudens",
    "Saint-Geniès-de-Malgoirès",
    "Saint-Genouph",
    "Saint-Georges-d'Aurac",
    "Saint-Georges-de-Commiers",
    "Saint-Georges-de-Luzençon",
    "Saint-Georges-de-Reneins",
    "Saint-Geours-de-Maremne",
    "Saint-Germain - Saint-Rémy",
    "Saint-Germain-au-Mont-d'Or",
    "Saint-Germain-des-Fossés",
    "Saint-Germain-du-Puy",
    "Saint-Germain-en-Laye Bel-Air - Fourqueux",
    "Saint-Germain-les-Belles",
    "Saint-Germain-sur-Ille",
    "Saint-Gervais-les-Bains Le Fayet",
    "Saint-Gildas-des-Bois",
    "Saint-Gilles Lycée Haut-Rhin",
    "Saint-Gilles-Croix-de-Vie",
    "Saint-Gratien",
    "Saint-Hilaire - Brizambourg",
    "Saint-Hilaire - Saint-Nazaire",
    "Saint-Hilaire-au-Temple",
    "Saint-Hilaire-de-Chaléons",
    "Saint-Hilaire-de-Riez",
    "Saint-Hilaire-sur-Helpe",
    "Saint-Jacques-de-la-Lande",
    "Saint-Jean-d'Angély",
    "Saint-Jean-de-Losne",
    "Saint-Jean-de-Luz - Ciboure",
    "Saint-Jean-de-Maurienne Arvan",
    "Saint-Jean-de-Verges",
    "Saint-Jean-Pied-de-Port",
    "Saint-Jodard",
    "Saint-Jory",
    "Saint-Joseph le Castellas",
    "Saint-Julien - Clénay",
    "Saint-Julien les Fumades",
    "Saint-Julien-du-Sault",
    "Saint-Julien-en-Genevois",
    "Saint-Junien",
    "Saint-Just-en-Chaussée",
    "Saint-Laurent - Gainneville",
    "Saint-Laurent-d'Aigouze",
    "Saint-Laurent-de-la-Prée - Fouras",
    "Saint-Laurent-du-Var",
    "Saint-Laurent-en-Grandvaux",
    "Saint-Léger-sur-Dheune",
    "Saint-Léonard-de-Noblat",
    "Saint-Léon-sur-l'Isle",
    "Saint-Leu-d'Esserent",
    "Saint-Leu-la-Forêt",
    "Saint-Lô",
    "Saint-Lothain",
    "Saint-Loubès",
    "Saint-Louis",
    "Saint-Louis La Chaussée",
    "Saint-Louis les Aygalades",
    "Saint-Macaire",
    "Saint-Maixent-L'École",
    "Saint-Malo",
    "Saint-Mammès",
    "Saint-Marcel",
    "Saint-Marcel en Dombes",
    "Saint-Marcellin",
    "Saint-Mariens - Saint-Yzan",
    "Saint-Mars-la-Brière",
    "Saint-Martin d'Étampes",
    "Saint-Martin du Touch",
    "Saint-Martin-Bellevue",
    "Saint-Martin-de-Crau",
    "Saint-Martin-d'Oney",
    "Saint-Martin-du-Mont",
    "Saint-Martin-du-Vivier",
    "Saint-Martin-le-Beau",
    "Saint-Martory",
    "Saint-Mathurin-sur-Loire",
    "Saint-Maurice-de-Beynost",
    "Saint-Médard-de-Guizières",
    "Saint-Médard-d'Eyrans",
    "Saint-Médard-sur-Ille",
    "Saint-Michel - Valloire",
    "Saint-Michel Notre-Dame",
    "Saint-Michel-sur-Meurthe",
    "Saint-Michel-sur-Orge",
    "Saint-Nabord",
    "Saint-Nazaire",
    "Saint-Nom-la-Bretèche Forêt de Marly",
    "Saint-Omer",
    "Saint-Omer-en-Chaussée",
    "Saint-Ouen",
    "Saint-Ouen-l'Aumône",
    "Saint-Ouen-l'Aumône Liesse",
    "Saint-Ouen-l'Aumône Quartier de l'Église",
    "Saint-Paterne-Racan",
    "Saint-Patrice",
    "Saint-Paul-de-Varax",
    "Saint-Pé-de-Bigorre",
    "Saint-Péray",
    "Saint-Piat",
    "Saint-Pierre-d'Albigny",
    "Saint-Pierre-d'Aurillac",
    "Saint-Pierre-de-Chignac",
    "Saint-Pierre-des-Corps",
    "Saint-Pierre-du-Vauvray",
    "Saint-Pierre-en-Faucigny",
    "Saint-Pierre-la-Cour",
    "Saint-Pierre-le-Moûtier",
    "Saint-Pierre-Quiberon",
    "Saint-Pierre-sur-Dives",
    "Saint-Pol-de-Léon",
    "Saint-Pol-sur-Ternoise",
    "Saint-Priest",
    "Saint-Priest-Taurion",
    "Saint-Quentin",
    "Saint-Quentin en Yvelines",
    "Saint-Quentin-Fallavier",
    "Saint-Rambert-d'Albon",
    "Saint-Rambert-en-Bugey",
    "Saint-Raphaël",
    "Saint-Remy-en-l'Eau",
    "Saint-Roch",
    "Saint-Romain-de-Popey",
    "Saint-Romain-le-Puy",
    "Saint-Rome-de-Cernon",
    "Saint-Saturnin-lès-Avignon",
    "Saint-Savinien",
    "Saint-Saviol",
    "Saint-Sébastien",
    "Saint-Sébastien Frêne Rond",
    "Saint-Sébastien Pas Enchantés",
    "Saint-Senoux - Pléchâtel",
    "Saint-Seurin-sur-l'Isle",
    "Saint-Sever",
    "Saint-Sulpice - Auteuil",
    "Saint-Sulpice - Izon",
    "Saint-Sulpice (Tarn)",
    "Saint-Sulpice-Laurière",
    "Saint-Symphorien-de-Marmagne",
    "Saint-Thégonnec",
    "Saint-Vallier sur Rhône",
    "Saint-Victor - Thizy",
    "Saint-Victor-l'Abbaye",
    "Saint-Victurnien",
    "Saint-Vincent le Château",
    "Saint-Vincent-de-Tyrosse",
    "Saint-Vit",
    "Saint-Yrieix-la-Perche",
    "Salbris",
    "Salindres",
    "Sallanches - Combloux - Megève",
    "Sallaumines",
    "Salles-Courbatiès",
    "Salomé",
    "Salon-de-Provence",
    "Salses-le-Château",
    "Sannois",
    "Sanry-sur-Nied",
    "Santenay les Bains",
    "Santes",
    "Santeuil - Le Perchay",
    "Saône",
    "Sarcelles - Saint-Brice",
    "Sarlat-la-Canéda",
    "Sarliève - Cournon",
    "Sarralbe",
    "Sarrance",
    "Sarrebourg",
    "Sarreguemines",
    "Sarreguemines-Est",
    "Sarreinsming",
    "Sarre-Union",
    "Sartrouville",
    "Sathonay - Rillieux",
    "Saubusse",
    "Saujon",
    "Saulieu",
    "Saulon",
    "Saulxures",
    "Saumur",
    "Sausset-les-Pins",
    "Sauto",
    "Sauveboeuf",
    "Sauveterre-la-Lémance",
    "Savenay",
    "Savennières - Béhuard",
    "Saverdun",
    "Saverne",
    "Savigny-le-Temple - Nandy",
    "Savigny-sur-Orge",
    "Savonnières",
    "Savy-Berlette",
    "Sceaux - Boëssé",
    "Scherwiller",
    "Schirmeck - La Broque",
    "Schopperten",
    "Schweighouse-sur-Moder",
    "Schwindratzheim",
    "Seclin",
    "Sedan",
    "Sées",
    "Sélestat",
    "Selles-Saint-Denis",
    "Selles-sur-Cher",
    "Seltz",
    "Sémalens",
    "Sénas",
    "Sennecey-le-Grand",
    "Senozan",
    "Sens",
    "Séon Saint-Henri",
    "Septèmes-les-Vallons",
    "Sept-Saulx",
    "Serdinya",
    "Sérézin-du-Rhône",
    "Sérifontaine",
    "Sermaise",
    "Sermizelles - Vézelay",
    "Serqueux",
    "Serquigny",
    "Serres",
    "Serrigny",
    "Servas - Lent",
    "Servon-sur-Vilaine",
    "Servoz",
    "Sessenheim",
    "Sète",
    "Seugy",
    "Seurre",
    "Sevenans",
    "Sévérac",
    "Sévérac-d'Aveyron",
    "Sevran - Livry",
    "Sevran Beaudottes",
    "Sèvres - Ville-d'Avray",
    "Sèvres Rive Gauche",
    "Seyssel - Corbonod",
    "Sierck-les-Bains",
    "Sierentz",
    "Sigournais",
    "Sillé-le-Guillaume",
    "Sillery",
    "Simandre-sur-Suran",
    "Simiane",
    "Sincey-lès-Rouvray",
    "Sin-le-Noble",
    "Siorac-en-Périgord",
    "Sisteron",
    "Soissons",
    "Solignac - Le Vigen",
    "Solliès-Pont",
    "Somain",
    "Sommery",
    "Sorgues - Châteauneuf-du-Pape",
    "Sospel",
    "Sotteville-lès-Rouen",
    "Sougy",
    "Souillac",
    "Soulac-sur-Mer",
    "Soultz-sous-Forêts",
    "Souppes - Château-Landon",
    "Sous le Bois",
    "St Jean sur Veyle",
    "ST Joseph le Castellas",
    "St Ours les Roches",
    "Stade de France Saint-Denis",
    "Staffelfelden",
    "Stains La Cerisaie T11",
    "St-Antoine",
    "St-Barthélémy",
    "St-Capraise-de-Lalinde",
    "Ste-Colombe-les-Vienne-St-Romain-en-Gal",
    "Steenbecque",
    "Steenwerck",
    "Steinbourg",
    "St-Éloi",
    "St-Éloy",
    "Stephansfeld",
    "St-Gervais-Chateauneuf",
    "St-Hilaire",
    "St-Julien (Côtes-d'Armor)",
    "St-Julien-Changy",
    "St-Julien-L'Ars",
    "St-Martin-de-Bouillac",
    "St-Martin-Sail-les-Bains",
    "St-Mesmin-le-Vieux",
    "St-Michel-sur-Charente",
    "Strasbourg",
    "Strasbourg Roethig",
    "Strazeele",
    "Sucé-sur-Erdre",
    "Suèvres",
    "Surdon",
    "Suresnes Mont Valérien",
    "Surgères",
    "Survilliers - Fosses",
    "Sury-le-Comtal",
    "Tacoignières - Richebourg",
    "Taconnaz",
    "Tagolsheim",
    "Taillebourg",
    "Tain-l'Hermitage - Tournon",
    "Tantonville",
    "Tanus",
    "Tarare",
    "Tarascon",
    "Tarascon-sur-Ariège",
    "Tarbes",
    "Tassin",
    "Taulé-Henvic",
    "Taverny",
    "Teillé",
    "Teillet-Argenty",
    "Templeuve",
    "Tenay - Hauteville",
    "Tende",
    "Tergnier",
    "Ternand",
    "Ternay",
    "Terrasson-Lavilledieu",
    "Tessonnières",
    "Teting-sur-Nied",
    "Thann",
    "Thann Centre",
    "Thann Saint-Jacques",
    "Thaon",
    "Theillay",
    "Thenissey",
    "Thenon",
    "Théoule-sur-Mer",
    "Thésée",
    "Thézy-Glimont",
    "Thiaville-sur-Meurthe",
    "Thiel-sur-Acolin",
    "Thiennes",
    "Thiers",
    "Thieux - Nantouillet",
    "Thionville",
    "Thiviers",
    "Thomery",
    "Thonon-les-Bains",
    "Thouaré-sur-Loire",
    "Thouars",
    "Thourotte",
    "Thuès Carença",
    "Thuès les Bains",
    "Thun le Paradis",
    "Tieffenbach - Struth",
    "Tiercé",
    "Tillières-sur-Avre",
    "Tincques",
    "Tonnay-Charente",
    "Tonneins",
    "Tonnerre",
    "Torfou-Sèvremoine",
    "Torpes - Boussières",
    "Touët-de-l'Escarène",
    "Toul",
    "Toulon",
    "Toulon Sainte-Musse",
    "Toulouse Matabiau",
    "Tourcoing",
    "Tournan-en-Brie",
    "Tournay",
    "Tournemire - Roquefort",
    "Tournus",
    "Tours",
    "Tourville-la-Rivière",
    "Toury",
    "Tracy - Sancerre",
    "Traou Nez",
    "Trappes",
    "Trégonneau - Squiffiec",
    "Trélazé",
    "Trémolat",
    "Trentels Ladignac",
    "Tricot",
    "Trie-Château",
    "Triel-sur-Seine",
    "Trilport",
    "Trith-Saint-Léger",
    "Trois Chênes",
    "Trois-Puits",
    "Tronsanges",
    "Trouville - Deauville",
    "Troyes",
    "Tulle",
    "Tullins Fures",
    "Turckheim",
    "Turenne",
    "Uchaud",
    "Uckange",
    "Ur - Les Escaldes",
    "Urçay",
    "Urmatt",
    "Urt",
    "Us",
    "Ussel",
    "Ustaritz Jatxou",
    "Uzerche",
    "Vaas",
    "Vaires - Torcy",
    "Val d'Argenteuil",
    "Val de Fontenay",
    "Valdahon",
    "Valdahon Camp Militaire",
    "Val-de-Reuil",
    "Val-de-Vesle",
    "Valençay",
    "Valence d'Agen",
    "Valence TGV Rhône-Alpes Sud",
    "Valence Ville",
    "Valenciennes",
    "Valergues - Lansargues",
    "Valleiry",
    "Valleroy - Moineville",
    "Vallon-en-Sully",
    "Vallorcine",
    "Valmondois",
    "Valognes",
    "Vandières",
    "Vannes",
    "Vanves - Malakoff",
    "Varades - Saint-Florent le Vieil",
    "Varangéville - Saint-Nicolas",
    "Varennes-sur-Allier",
    "Varennes-sur-Fouzon",
    "Varetz",
    "Varilhes",
    "Vauboyen",
    "Vaucelles",
    "Vaucresson",
    "Vaudagne",
    "Vaudagne",
    "Vaulry",
    "Vaumoise",
    "Vauvert",
    "Vauxaillon",
    "Vaux-sur-Seine",
    "Vauzelles",
    "Vayrac",
    "Vayres",
    "Veauche - Saint-Galmier",
    "Veigné",
    "Velars-sur-Ouche",
    "Vélines",
    "Vendenheim",
    "Vendeuvre-sur-Barse",
    "Vendôme",
    "Vendôme - Villiers-sur-Loir TGV",
    "Venerque - Vernet",
    "Vénissieux",
    "Verdun",
    "Véretz - Montlouis",
    "Vergèze - Codognan",
    "Vermenton",
    "Vernaison",
    "Verneuil-l'Étang",
    "Verneuil-sur-Avre",
    "Verneuil-sur-Serre",
    "Verneuil-sur-Vienne",
    "Vernon - Giverny",
    "Vernouillet - Verneuil",
    "Vernou-la-Celle-sur-Seine",
    "Vern-sur-Seiche",
    "Verrey-sous-Salmaise",
    "Versailles Chantiers",
    "Versailles Château Rive Gauche",
    "Versailles Rive Droite",
    "Versigny",
    "Vert Galant",
    "Vertaizon",
    "Vertou",
    "Vervins",
    "Verzeille",
    "Vesoul",
    "Veuves - Monteaux",
    "Veynes Dévoluy",
    "Vézelise",
    "Viaduc Sainte-Marie",
    "Viarmes",
    "Vias",
    "Viazac",
    "Vic - Mireval",
    "Vichy",
    "Vic-le-Comte",
    "Vic-sur-Cère",
    "Vidauban",
    "Vieilleville",
    "Vielmur-sur-Agout",
    "Vienne",
    "Vierzon",
    "Vierzon Forges",
    "Vierzy",
    "Viescamp sous Jallès",
    "Viescamp-sous-Jallès",
    "Vieux-Thann",
    "Vieux-Thann Zone Industrielle",
    "Viévola",
    "Vif",
    "Vigeois",
    "Vigneux-sur-Seine",
    "Vignols - Saint-Solve",
    "Vignory",
    "Villabé",
    "Villaines-sous-Bois",
    "Villars-les-Dombes",
    "Villechaud",
    "Villedieu-Chanliau",
    "Villedieu-les-Poêles",
    "Villefort",
    "Villefranche - Vernet-les-Bains",
    "Villefranche-de-Lauragais",
    "Villefranche-de-Rouergue",
    "Villefranche-du-Périgord",
    "Villefranche-sur-Cher",
    "Villefranche-sur-Mer",
    "Villefranche-sur-Saône",
    "Villefranque",
    "Villeherviers",
    "Villenave-d'Ornon",
    "Villeneuve Triage",
    "Villeneuve-d'Aveyron",
    "Villeneuve-la-Comtesse",
    "Villeneuve-la-Guyard",
    "Villeneuve-le-Roi",
    "Villeneuve-lès-Maguelone",
    "Villeneuve-Loubet",
    "Villeneuve-Saint-Georges",
    "Villeneuve-sur-Allier",
    "Villeneuve-sur-Yonne",
    "Villennes-sur-Seine",
    "Villenouvelle",
    "Villeparisis - Mitry-le-Neuf",
    "Villeperdue",
    "Villepinte",
    "Villepreux - Les Clayes",
    "Villereversure",
    "Villers sur Thère",
    "Villers-Bretonneux",
    "Villers-Cotterêts",
    "Villers-les-Pots",
    "Villers-Saint-Paul",
    "Villers-Saint-Sépulcre",
    "Villers-sur-Mer",
    "Villetaneuse Université T11",
    "Villiers - Neauphle - Pontchartrain",
    "Villiers Montbarbin",
    "Villiers-le-Bel - Gonesse - Arnouville",
    "Villiers-sur-Marne - Le Plessis-Trévise",
    "Vimy",
    "Vinay",
    "Vinça",
    "Vincelles",
    "Vincey",
    "Vions - Chanaz",
    "Vire",
    "Vireux-Molhain",
    "Virieu sur Bourbre",
    "Virieu-le-Grand - Belley",
    "Viroflay Rive Droite",
    "Viroflay Rive Gauche",
    "Virville - Manneville",
    "Viry-Châtillon",
    "Viry-Noureuil",
    "Vis à Marles",
    "Vitré",
    "Vitrolles Aéroport Marseille Provence",
    "Vitry-en-Artois",
    "Vitry-le-François",
    "Vitry-sur-Seine",
    "Vittel",
    "Viviers-du-Lac",
    "Viviez - Decazeville",
    "Vivoin - Beaumont",
    "Vivonne",
    "Voiron",
    "Voivres-lès-le-Mans",
    "Volvic",
    "Vonnas",
    "Voreppe",
    "Vorey",
    "Vosves",
    "Vougeot - Gilly-lès-Cîteaux",
    "Voujeaucourt",
    "Voutré",
    "Voves",
    "Voyenne",
    "Vraincourt - Viéville",
    "Vrigne-Meuse",
    "Vulaines-sur-Seine - Samoreau",
    "Wacquemoulin",
    "Walbach",
    "Walbourg",
    "Walheim",
    "Waligator Parc",
    "Wallers",
    "Wambaix",
    "Wambrechies",
    "Watten - Éperlecques",
    "Wattignies - Templemars",
    "Wavrin",
    "Wesserling",
    "Weyersheim",
    "Wiencourt-l'Équipée",
    "Wihr-au-Val - Soultzbach",
    "Willer-sur-Thur",
    "Wilwisheim",
    "Wimille - Wimereux",
    "Wingen-sur-Moder",
    "Wisches",
    "Wissembourg",
    "Wittring",
    "Woincourt",
    "Woippy",
    "Xertigny",
    "Xeuilley",
    "Ychoux",
    "Yerres",
    "Yffiniac",
    "Ygos-Saint-Saturnin",
    "Ytrac",
    "Yvetot",
    "Zetting",
    "Zillisheim"];