export const stationNames = ["Abbey Wood",
    "Aber",
    "Abercynon",
    "Aberdare",
    "Aberdeen",
    "Aberdour",
    "Aberdovey",
    "Abererch",
    "Abergavenny",
    "Abergele & Pensarn",
    "Aberystwyth",
    "Abingdon (Bus)",
    "Accrington",
    "Achanalt",
    "Achnasheen",
    "Achnashellach",
    "Acklington",
    "Acle",
    "Acocks Green",
    "Acton Bridge",
    "Acton Central",
    "Acton Main Line",
    "Adderley Park",
    "Addiewell",
    "Addlestone",
    "Adisham",
    "Adlington (Cheshire)",
    "Adlington (Lancashire)",
    "Adwick",
    "Aigburth",
    "Ainsdale",
    "Aintree",
    "Airbles",
    "Airdrie",
    "Albany Park",
    "Albrighton",
    "Alderley Edge",
    "Aldermaston",
    "Aldershot",
    "Aldrington",
    "Alexandra Palace",
    "Alexandra Parade",
    "Alexandria",
    "Alfreton",
    "Allens West",
    "Alloa",
    "Alness",
    "Alnmouth",
    "Alresford",
    "Alsager",
    "Althorne",
    "Althorpe",
    "Altnabreac",
    "Alton",
    "Alton Towers (Bus)",
    "Altrincham",
    "Alvechurch",
    "Ambergate",
    "Amberley",
    "Amersham",
    "Ammanford",
    "Ampfield School (Bus)",
    "Amsterdam CS",
    "Ancaster",
    "Anderston",
    "Andover",
    "Anerley",
    "Angmering",
    "Annan",
    "Anniesland",
    "Ansdell & Fairhaven",
    "Apperley Bridge",
    "Appleby",
    "Appledore (Kent)",
    "Appleford",
    "Appley Bridge",
    "Apsley",
    "Arbroath",
    "Ardgay",
    "Ardlui",
    "Ardrossan Harbour",
    "Ardrossan South Beach",
    "Ardrossan Town",
    "Ardwick",
    "Argyle Street",
    "Arisaig",
    "Arlesey",
    "Armadale",
    "Armadale (Bus)",
    "Armathwaite",
    "Arnside",
    "Arram",
    "Arrochar & Tarbet",
    "Arundel",
    "Ascot",
    "Ascott-under-Wychwood",
    "Ash",
    "Ash Vale",
    "Ashburys",
    "Ashchurch for Tewkesbury",
    "Ashfield",
    "Ashford (Surrey)",
    "Ashford International",
    "Ashley",
    "Ashtead",
    "Ashton-under-Lyne",
    "Ashurst",
    "Ashurst New Forest",
    "Ashwell & Morden",
    "Askam",
    "Aslockton",
    "Aspatria",
    "Aspley Guise",
    "Aston",
    "Atherstone",
    "Atherton",
    "Attadale",
    "Attenborough",
    "Attercliffe (Tram)",
    "Attleborough",
    "Auchinleck",
    "Audley End",
    "Aughton Park",
    "Avebury (Bus)",
    "Aviemore",
    "Avignon",
    "Avoncliff",
    "Avonmouth",
    "Axminster",
    "Aylesbury",
    "Aylesbury Vale Parkway",
    "Aylesford",
    "Aylesham",
    "Ayr",
    "Bache",
    "Baglan",
    "Bagshot",
    "Baildon",
    "Baillieston",
    "Baker Street Underground",
    "Bakewell (Bus)",
    "Balcombe",
    "Baldock",
    "Balham",
    "Balloch",
    "Balmossie",
    "Bamber Bridge",
    "Bamford",
    "Banavie",
    "Banbury",
    "Bangor (Gwynedd)",
    "Bank Hall",
    "Banstead",
    "Barassie",
    "Barbican Underground",
    "Bardon Mill",
    "Bare Lane",
    "Bargeddie",
    "Bargoed",
    "Barking",
    "Barking Riverside",
    "Barking Underground",
    "Barlaston",
    "Barlaston Orchard Place (Bus)",
    "Barming",
    "Barmouth",
    "Barnehurst",
    "Barnes",
    "Barnes Bridge",
    "Barnetby",
    "Barnham",
    "Barnhill",
    "Barnsley",
    "Barnsley (Bus)",
    "Barnstaple",
    "Barnt Green",
    "Barons Court Underground",
    "Barrhead",
    "Barrhill",
    "Barrow Haven",
    "Barrow-in-Furness",
    "Barrow-upon-Soar",
    "Barry",
    "Barry Docks",
    "Barry Island",
    "Barry Links",
    "Barton-on-Humber",
    "Basildon",
    "Basingstoke",
    "Bat & Ball",
    "Bath Bus Station",
    "Bath Spa",
    "Bathgate",
    "Batley",
    "Battersby",
    "Battersea Park",
    "Battle",
    "Battlesbridge",
    "Bayford",
    "Beaconsfield",
    "Bearley",
    "Bearsden",
    "Bearsted",
    "Beasdale",
    "Beaulieu Road",
    "Beauly",
    "Bebington",
    "Beccles",
    "Beckenham Hill",
    "Beckenham Junction",
    "Bedford",
    "Bedford (Bus)",
    "Bedford St Johns",
    "Bedhampton",
    "Bedminster",
    "Bedworth",
    "Bedwyn",
    "Beeston",
    "Bekesbourne",
    "Belfast Donegall Quay (Bus)",
    "Belfast Port",
    "Belle Vue",
    "Bellgrove",
    "Bellingham",
    "Bellshill",
    "Belmont",
    "Belper",
    "Beltring",
    "Belvedere",
    "Bempton",
    "Ben Rhydding",
    "Benfleet",
    "Bentham",
    "Bentley (Hampshire)",
    "Bentley (South Yorkshire)",
    "Benton (T & W Metro)",
    "Bere Alston",
    "Bere Ferrers",
    "Berkhamsted",
    "Berkswell",
    "Bermuda Park (Nuneaton)",
    "Berney Arms",
    "Berry Brow",
    "Berrylands",
    "Berwick (Sussex)",
    "Berwick-upon-Tweed",
    "Bescar Lane",
    "Bescot Stadium",
    "Betchworth",
    "Bethnal Green",
    "Betws-y-Coed",
    "Beverley",
    "Bexhill",
    "Bexley",
    "Bexleyheath",
    "Bicester (Bus)",
    "Bicester North",
    "Bicester Village",
    "Bickley",
    "Bidston",
    "Biggleswade",
    "Bilbrook",
    "Billericay",
    "Billingham",
    "Billingshurst",
    "Bingham",
    "Bingley",
    "Birchgrove",
    "Birchington-on-Sea",
    "Birchwood",
    "Birkbeck",
    "Birkdale",
    "Birkenhead Central",
    "Birkenhead North",
    "Birkenhead Park",
    "Birmingham Airport (Bus)",
    "Birmingham International",
    "Birmingham Moor Street",
    "Birmingham NEC (Bus)",
    "Birmingham New Street",
    "Birmingham Snow Hill",
    "Bishop Auckland",
    "Bishopbriggs",
    "Bishops Lydeard",
    "Bishops Lydeard (Bus)",
    "Bishops Stortford",
    "Bishopstone",
    "Bishopton",
    "Bitterne",
    "Blackburn",
    "Blackheath",
    "Blackhorse Road",
    "Blackpool North",
    "Blackpool Pleasure Beach",
    "Blackpool South",
    "Blackridge",
    "Blackrod",
    "Blackwater",
    "Blackwood (Bus)",
    "Blaenau Ffestiniog",
    "Blair Atholl",
    "Blairhill",
    "Blake Street",
    "Blakedown",
    "Blantyre",
    "Blaydon",
    "Bleasby",
    "Bletchley",
    "Bloxwich",
    "Bloxwich North",
    "Blundellsands & Crosby",
    "Blythe Bridge",
    "Boat of Garten Post Off (Bus)",
    "Bodmin Parkway",
    "Bodmin TSB Bank (Bus)",
    "Bodorgan",
    "Bognor Regis",
    "Bogston",
    "Bolton",
    "Bolton-on-Dearne",
    "Bond Street",
    "Bookham",
    "Bootle",
    "Bootle New Strand",
    "Bootle Oriel Road",
    "Bordesley",
    "Bordon Camp (Bus)",
    "Borough Green & Wrotham",
    "Borth",
    "Bosham",
    "Boston",
    "Botley",
    "Bottesford",
    "Bourg St Maurice",
    "Bourne End",
    "Bournemouth",
    "Bournemouth Hurn Airport (Bus)",
    "Bournville",
    "Bow Brickhill",
    "Bow Street",
    "Bowes Park",
    "Bowling",
    "Box Hill & Westhumble",
    "Bracknell",
    "Bradford Forster Square",
    "Bradford Interchange",
    "Bradford-on-Avon",
    "Brading",
    "Braintree",
    "Braintree Freeport",
    "Bramhall",
    "Bramley (Hampshire)",
    "Bramley (West Yorkshire)",
    "Brampton (Cumbria)",
    "Brampton (Suffolk)",
    "Branchton",
    "Brandon",
    "Branksome",
    "Braystones",
    "Brecon Square (Bus)",
    "Bredbury",
    "Breich",
    "Brent Cross West",
    "Brentford",
    "Brentwood",
    "Bricket Wood",
    "Bridge of Allan",
    "Bridge of Orchy",
    "Bridgend",
    "Bridgeton",
    "Bridgwater",
    "Bridlington",
    "Brierfield",
    "Brigg",
    "Brighouse",
    "Brighton",
    "Brimsdown",
    "Brinnington",
    "Bristol Intl Airport (Bus)",
    "Bristol Parkway",
    "Bristol Temple Gate (Bus)",
    "Bristol Temple Meads",
    "Brithdir",
    "British Steel Redcar",
    "Briton Ferry",
    "Brixton",
    "Broad Green",
    "Broadbottom",
    "Broadstairs",
    "Brockenhurst",
    "Brockholes",
    "Brockley",
    "Brockley Whins (T & W Metro)",
    "Brodick (Bus)",
    "Bromborough",
    "Bromborough Rake",
    "Bromley Cross",
    "Bromley North",
    "Bromley South",
    "Bromsgrove",
    "Brondesbury",
    "Brondesbury Park",
    "Brookmans Park",
    "Brookwood",
    "Broome",
    "Broomfleet",
    "Brora",
    "Brough",
    "Broughty Ferry",
    "Broxbourne",
    "Bruce Grove",
    "Brundall",
    "Brundall Gardens",
    "Brunstane",
    "Brunswick",
    "Brussels Midi",
    "Bruton",
    "Bryn",
    "Buckenham",
    "Buckingham (Bus)",
    "Buckley",
    "Bucknell",
    "Buckshaw Parkway",
    "Bude Strand (Bus)",
    "Bugle",
    "Builth Road",
    "Bulwell",
    "Bures",
    "Burgess Hill",
    "Burley Park",
    "Burley-in-Wharfedale",
    "Burnage",
    "Burneside",
    "Burnham",
    "Burnham Market (Bus)",
    "Burnham-on-Crouch",
    "Burnley Barracks",
    "Burnley Central",
    "Burnley Manchester Road",
    "Burnside",
    "Burntisland",
    "Burscough Bridge",
    "Burscough Junction",
    "Bursledon",
    "Burton Joyce",
    "Burton-on-Trent",
    "Bury Metrolink (Bus)",
    "Bury St Edmunds",
    "Busby",
    "Bush Hill Park",
    "Bushey",
    "Butlers Lane",
    "Buxted",
    "Buxton",
    "Buxton (Bus)",
    "Byfleet & New Haw",
    "Bynea",
    "Cadoxton",
    "Caerau Park (Bus)",
    "Caerau Square (Bus)",
    "Caergwrle",
    "Caerphilly",
    "Caersws",
    "Cairnyan Port",
    "Calais Frethun",
    "Caldercruix",
    "Caldicot",
    "Caledonian Rd & Barnsbury",
    "Callington (Bus)",
    "Calne (Bus)",
    "Calstock",
    "Cam & Dursley",
    "Camberley",
    "Camborne",
    "Cambridge",
    "Cambridge (Bus)",
    "Cambridge Heath",
    "Cambridge North",
    "Cambuslang",
    "Camden Road",
    "Camelon",
    "Canada Water",
    "Canary Wharf (Elizabeth line)",
    "Canley",
    "Canna (Bus)",
    "Cannock",
    "Canonbury",
    "Canterbury East",
    "Canterbury West",
    "Cantley",
    "Capenhurst",
    "Carbis Bay",
    "Carbrook (Tram)",
    "Cardenden",
    "Cardiff Bay",
    "Cardiff Central",
    "Cardiff Central Bus Stn",
    "Cardiff Intl Airport (Bus)",
    "Cardiff Queen Street",
    "Cardonald",
    "Cardross",
    "Carfin",
    "Cark",
    "Carlisle",
    "Carlton",
    "Carluke",
    "Carmarthen",
    "Carmyle",
    "Carnforth",
    "Carnoustie",
    "Carntyne",
    "Carpenders Park",
    "Carrbridge",
    "Carshalton",
    "Carshalton Beeches",
    "Carstairs",
    "Cartsdyke",
    "Castle Bar Park",
    "Castle Cary",
    "Castle Howard (Bus)",
    "Castle Square (Tram)",
    "Castlebay, Barra (Bus)",
    "Castleford",
    "Castleton",
    "Castleton Moor",
    "Caterham",
    "Catford",
    "Catford Bridge",
    "Cathays",
    "Cathcart",
    "Cattal",
    "Catterick Camp Centre (Bus)",
    "Catterick Garrison (Bus)",
    "Catterick Garrison Tesco (Bus)",
    "Causeland",
    "Cefn-y-Bedd",
    "Chadwell Heath",
    "Chafford Hundred",
    "Chalfont & Latimer",
    "Chalkwell",
    "Chandlers Ford",
    "Chapel-en-le-Frith",
    "Chapeltown",
    "Chapleton",
    "Chappel & Wakes Colne",
    "Charing",
    "Charing Cross (Glasgow)",
    "Charlbury",
    "Charlton",
    "Chartham",
    "Chassen Road",
    "Chatelherault",
    "Chatham",
    "Chathill",
    "Chatsworth House (Bus)",
    "Cheadle Hulme",
    "Cheam",
    "Cheddington",
    "Chelford",
    "Chelmsford",
    "Chelsfield",
    "Cheltenham Spa",
    "Chepstow",
    "Cherry Tree",
    "Chertsey",
    "Cheshunt",
    "Chessington North",
    "Chessington South",
    "Chester",
    "Chester Road",
    "Chester-le-Street",
    "Chesterfield",
    "Chestfield & Swalecliffe",
    "Chetnole",
    "Chichester",
    "Chilham",
    "Chilworth",
    "Chingford",
    "Chinley",
    "Chinnor (Bus)",
    "Chippenham",
    "Chippenham Bath Road (Bus)",
    "Chippenham New Road (Bus)",
    "Chipping Norton West St (Bus)",
    "Chipstead",
    "Chirk",
    "Chislehurst",
    "Chiswick",
    "Cholsey",
    "Chorley",
    "Chorleywood",
    "Christchurch",
    "Christs Hospital",
    "Church & Oswaldtwistle",
    "Church Fenton",
    "Church Stretton",
    "Cilmeri",
    "City Thameslink",
    "Clacton-on-Sea",
    "Clandon",
    "Clapham (North Yorkshire)",
    "Clapham High Street",
    "Clapham Junction",
    "Clapton",
    "Clarbeston Road",
    "Clarkston",
    "Claverdon",
    "Claygate",
    "Cleethorpes",
    "Cleland",
    "Clifton",
    "Clifton Down",
    "Clitheroe",
    "Clock House",
    "Clunderwen",
    "Clydebank",
    "Coatbridge Central",
    "Coatbridge Sunnyside",
    "Coatdyke",
    "Cobham & Stoke d'Abernon",
    "Cockermouth (Bus)",
    "Cockfosters Underground",
    "Codsall",
    "Cogan",
    "Colchester",
    "Colchester Town",
    "Coleshill Parkway",
    "Coll (Bus)",
    "Collingham",
    "Collington",
    "Colne",
    "Colonsay (Bus)",
    "Colwall",
    "Colwyn Bay",
    "Combe",
    "Commondale",
    "Congleton",
    "Conisbrough",
    "Connel Ferry",
    "Conon Bridge",
    "Cononley",
    "Conway Park",
    "Conwy",
    "Cooden Beach",
    "Cookham",
    "Cooksbridge",
    "Coombe Junction Halt",
    "Copplestone",
    "Corbridge",
    "Corby",
    "Corby George Street (Bus)",
    "Corfe Castle",
    "Corkerhill",
    "Corkickle",
    "Corpach",
    "Corrour",
    "Corsham (Bus)",
    "Coryton",
    "Coseley",
    "Cosford",
    "Cosham",
    "Cottingham",
    "Cottingley",
    "Coulsdon South",
    "Coulsdon Town",
    "Coventry",
    "Coventry Arena",
    "Cowden",
    "Cowdenbeath",
    "Cradley Heath",
    "Craigendoran",
    "Craignure, Mull (Bus)",
    "Cramlington",
    "Cranbrook (Devon)",
    "Craven Arms",
    "Crawley",
    "Crayford",
    "Crediton",
    "Cressing",
    "Cressington",
    "Creswell",
    "Crewe",
    "Crewkerne",
    "Crews Hill",
    "Crianlarich",
    "Criccieth",
    "Cricket Inn Road (Tram)",
    "Cricklewood",
    "Croftfoot",
    "Crofton Park",
    "Cromer",
    "Cromford",
    "Crookston",
    "Cross Gates",
    "Crossflatts",
    "Crosshill",
    "Crosskeys",
    "Crossmyloof",
    "Croston",
    "Crouch Hill",
    "Crowborough",
    "Crowhurst",
    "Crowle",
    "Crowthorne",
    "Croxley Underground",
    "Croy",
    "Crystal Palace",
    "Cuddington",
    "Cuffley",
    "Culdrose RNAS (Bus)",
    "Culham",
    "Cullompton (Bus)",
    "Culrain",
    "Cumbernauld",
    "Cumbrae Slip (Bus)",
    "Cupar",
    "Curriehill",
    "Custom House",
    "Cuxton",
    "Cwmbach",
    "Cwmbran",
    "Cynghordy",
    "Dagenham Dock",
    "Dagenham East Underground",
    "Daisy Hill",
    "Dalgety Bay",
    "Dalmally",
    "Dalmarnock",
    "Dalmeny",
    "Dalmuir",
    "Dalreoch",
    "Dalry",
    "Dalston",
    "Dalston Junction",
    "Dalston Kingsland",
    "Dalton",
    "Dalwhinnie",
    "Danby",
    "Danescourt",
    "Danzey",
    "Darfield (Bus)",
    "Darlington",
    "Darnall",
    "Darsham",
    "Dartford",
    "Dartmouth (Bus)",
    "Darton",
    "Darwen",
    "Datchet",
    "Davenport",
    "Dawlish",
    "Dawlish Warren",
    "Deal",
    "Dean",
    "Dean Lane",
    "Deansgate",
    "Deganwy",
    "Deighton",
    "Delamere",
    "Denby Dale",
    "Denham",
    "Denham Golf Club",
    "Denmark Hill",
    "Dent",
    "Denton",
    "Deptford",
    "Derby",
    "Derby Road",
    "Dereham Market Place (Bus)",
    "Derker",
    "Devizes (Bus)",
    "Devonport",
    "Dewsbury",
    "Didcot Parkway",
    "Digby & Sowton",
    "Dilton Marsh",
    "Dinas Powys",
    "Dinas Rhondda",
    "Dingle Road",
    "Dingwall",
    "Dinsdale",
    "Dinting",
    "Disley",
    "Diss",
    "Dockyard",
    "Dodworth",
    "Dolau",
    "Doleham",
    "Dolgarrog",
    "Dolwyddelan",
    "Doncaster",
    "Doncaster North Bus Stn",
    "Dorchester South",
    "Dorchester West",
    "Dore",
    "Dorking",
    "Dorking Deepdene",
    "Dorking West",
    "Dormans",
    "Dorridge",
    "Douglas (Isle of Man)",
    "Dove Holes",
    "Dover Priory",
    "Dovercourt",
    "Dovey Junction",
    "Downham Market",
    "Drayton Green",
    "Drayton Park",
    "Drem",
    "Driffield",
    "Drigg",
    "Droitwich Spa",
    "Dronfield",
    "Drumchapel",
    "Drumfrochar",
    "Drumgelloch",
    "Drumry",
    "Dublin Ferryport",
    "Dublin Port (Stena)",
    "Duddeston",
    "Dudley Port",
    "Duffield",
    "Duirinish",
    "Duke Street",
    "Dullingham",
    "Dumbarton Central",
    "Dumbarton East",
    "Dumbreck",
    "Dumfries",
    "Dumpton Park",
    "Dun Laoghaire",
    "Dunbar",
    "Dunblane",
    "Duncraig",
    "Dundee",
    "Dunfermline Queen Margaret",
    "Dunfermline City",
    "Dunkeld & Birnam",
    "Dunlop",
    "Dunoon (Bus)",
    "Dunrobin Castle",
    "Duns (Bus)",
    "Dunstable (Bus)",
    "Dunster (Bus)",
    "Dunston",
    "Dunton Green",
    "Durham",
    "Durrington-on-Sea",
    "Dyce",
    "Dyffryn Ardudwy",
    "Eaglescliffe",
    "Ealing Broadway",
    "Earl's Court Underground",
    "Earlestown",
    "Earley",
    "Earlsfield",
    "Earlston, Borders (Bus)",
    "Earlswood (Surrey)",
    "Earlswood (West Midlands)",
    "East Boldon (T & W Metro)",
    "East Croydon",
    "East Didsbury",
    "East Dulwich",
    "East Farleigh",
    "East Garforth",
    "East Grinstead",
    "East Kilbride",
    "East Linton",
    "East Malling",
    "East Midlands Airport (Bus)",
    "East Midlands Parkway",
    "East Tilbury",
    "East Worthing",
    "Eastbourne",
    "Eastbrook",
    "Easterhouse",
    "Eastham Rake",
    "Eastleigh",
    "Eastrington",
    "Ebbsfleet International",
    "Ebbw Vale Parkway",
    "Ebbw Vale Town",
    "Eccles",
    "Eccles Road",
    "Eccleston Park",
    "Edale",
    "Eden Camp (Bus)",
    "Eden Park",
    "Eden Project (Bus)",
    "Edenbridge",
    "Edenbridge Town",
    "Edge Hill",
    "Edinburgh",
    "Edinburgh Airport (Bus or Tram",
    "Edinburgh Bus Station",
    "Edinburgh Gateway",
    "Edinburgh Park",
    "Edmonton Green",
    "Effingham Junction",
    "Eggesford",
    "Egham",
    "Egton",
    "Eigg (Bus)",
    "Elephant & Castle",
    "Elephant & Castle Underground",
    "Elgin",
    "Ellesmere Port",
    "Elmers End",
    "Elmstead Woods",
    "Elmswell",
    "Elsecar",
    "Elsenham",
    "Elstree & Borehamwood",
    "Eltham",
    "Elton & Orston",
    "Ely",
    "Emerson Park",
    "Emsworth",
    "Energlyn & Churchill Park",
    "Enfield Chase",
    "Enfield Lock",
    "Enfield Town",
    "Entwistle",
    "Epsom",
    "Epsom Downs",
    "Erdington",
    "Eridge",
    "Erith",
    "Esher",
    "Eskbank",
    "Essex Road",
    "Etchingham",
    "Euxton Balshaw Lane",
    "Evesham",
    "Ewell East",
    "Ewell West",
    "Exeter Airport (Bus)",
    "Exeter Central",
    "Exeter St Davids",
    "Exeter St Thomas",
    "Exhibition Centre",
    "Exmouth",
    "Exton",
    "Eynsford",
    "Eynsham Church (Bus)",
    "Failsworth",
    "Fairbourne",
    "Fairfield",
    "Fairlie",
    "Fairwater",
    "Falconwood",
    "Falkirk Grahamston",
    "Falkirk High",
    "Falls of Cruachan",
    "Falmer",
    "Falmouth Docks",
    "Falmouth Town",
    "Fareham",
    "Farnborough (Main)",
    "Farnborough North",
    "Farncombe",
    "Farnham",
    "Farningham Road",
    "Farnworth",
    "Farringdon",
    "Fauldhouse",
    "Faversham",
    "Faygate",
    "Fazakerley",
    "Fearn",
    "Featherstone",
    "Felixstowe",
    "Fellgate (T & W Metro)",
    "Feltham",
    "Feniton",
    "Fenny Stratford",
    "Fernhill",
    "Ferriby",
    "Ferryside",
    "Ffairfach",
    "Filey",
    "Filton Abbey Wood",
    "Finchley Road & Frognal",
    "Finsbury Park",
    "Finstock",
    "Fishbourne (West Sussex)",
    "Fishersgate",
    "Fishguard & Goodwick",
    "Fishguard Harbour",
    "Fiskerton",
    "Fitzalan Square (Tram)",
    "Fitzwilliam",
    "Five Ways",
    "Flamingo Land (Bus)",
    "Fleet",
    "Flimby",
    "Flint",
    "Flitwick",
    "Flixton",
    "Flowery Field",
    "Folkestone Central",
    "Folkestone Harbour (Bus)",
    "Folkestone West",
    "Ford",
    "Forest Gate",
    "Forest Hill",
    "Formby",
    "Forres",
    "Forsinard",
    "Fort Matilda",
    "Fort William",
    "Four Oaks",
    "Fowey (Bus)",
    "Foxfield",
    "Foxton",
    "Frant",
    "Fratton",
    "Freshfield",
    "Freshford",
    "Frimley",
    "Frinton-on-Sea",
    "Frizinghall",
    "Frodsham",
    "Frome",
    "Frome Town (Bus)",
    "Fulwell",
    "Furness Vale",
    "Furze Platt",
    "Gainsborough Central",
    "Gainsborough Lea Road",
    "Galashiels",
    "Galashiels (Bus)",
    "Garelochhead",
    "Garforth",
    "Gargrave",
    "Garrowhill",
    "Garscadden",
    "Garsdale",
    "Garston (Hertfordshire)",
    "Garswood",
    "Gartcosh",
    "Garth (Mid Glamorgan)",
    "Garth (Powys)",
    "Garve",
    "Gathurst",
    "Gatley",
    "Gatwick Airport",
    "Georgemas Junction",
    "Gerrards Cross",
    "Gidea Park",
    "Giffnock",
    "Giggleswick",
    "Gilberdyke",
    "Gilfach Fargoed",
    "Gillingham (Dorset)",
    "Gillingham (Kent)",
    "Gilshochill",
    "Gipsy Hill",
    "Girvan",
    "Glaisdale",
    "Glan Conwy",
    "Glasgow Airport (Bus)",
    "Glasgow Central",
    "Glasgow Queen Street",
    "Glasshoughton",
    "Glastonbury (Bus)",
    "Glazebrook",
    "Gleneagles",
    "Glenfinnan",
    "Glengarnock",
    "Glenrothes with Thornton",
    "Glossop",
    "Gloucester",
    "Glynde",
    "Goathland",
    "Gobowen",
    "Godalming",
    "Godley",
    "Godstone",
    "Goldthorpe",
    "Goldthorpe (Bus)",
    "Golf Street",
    "Golspie",
    "Gomshall",
    "Goodmayes",
    "Goole",
    "Goostrey",
    "Gordon Hill",
    "Gorebridge",
    "Goring & Streatley",
    "Goring-by-Sea",
    "Gorton",
    "Gospel Oak",
    "Gourock",
    "Gourock Pier (Bus)",
    "Gowerton",
    "Goxhill",
    "Grange Park",
    "Grange-over-Sands",
    "Grangemouth (Bus)",
    "Grangetown",
    "Grantham",
    "Grateley",
    "Gravelly Hill",
    "Gravesend",
    "Grays",
    "Great Ayton",
    "Great Bentley",
    "Great Chesterford",
    "Great Coates",
    "Great Malvern",
    "Great Missenden",
    "Great Yarmouth",
    "Green Lane",
    "Green Road",
    "Greenbank",
    "Greenfaulds",
    "Greenfield",
    "Greenford",
    "Greenhithe for Bluewater",
    "Greenock Central",
    "Greenock West",
    "Greenwich",
    "Gretna Green",
    "Grimsby Docks",
    "Grimsby Town",
    "Grindleford",
    "Groombridge (Bus)",
    "Grosmont",
    "Grove Park",
    "Guide Bridge",
    "Guildford",
    "Guiseley",
    "Gunnersbury",
    "Gunnislake",
    "Gunton",
    "Gwersyllt",
    "Gypsy Lane",
    "Habrough",
    "Hackbridge",
    "Hackney Central",
    "Hackney Downs",
    "Hackney Wick",
    "Haddenham & Thame Parkway",
    "Haddiscoe",
    "Hadfield",
    "Hadley Wood",
    "Hag Fold",
    "Haggerston",
    "Hagley",
    "Hairmyres",
    "Hale",
    "Halesworth",
    "Halewood",
    "Halifax",
    "Hall Green",
    "Hall I' Th' Wood",
    "Hall Road",
    "Halling",
    "Haltwhistle",
    "Ham Street",
    "Hamble",
    "Hamilton Central",
    "Hamilton Square",
    "Hamilton West",
    "Hammersmith Underground",
    "Hammerton",
    "Hampden Park",
    "Hampstead Heath",
    "Hampton",
    "Hampton Court",
    "Hampton Wick",
    "Hampton-in-Arden",
    "Hamstead",
    "Hamworthy",
    "Hanborough",
    "Handforth",
    "Hanley (Bus)",
    "Hanwell",
    "Hapton",
    "Harlech",
    "Harlesden",
    "Harling Road",
    "Harlington",
    "Harlow Mill",
    "Harlow Town",
    "Harold Wood",
    "Harpenden",
    "Harrietsham",
    "Harringay",
    "Harringay Green Lanes",
    "Harrington",
    "Harrogate",
    "Harrow & Wealdstone",
    "Harrow-on-the-Hill",
    "Hartford",
    "Hartlebury",
    "Hartlepool",
    "Hartwood",
    "Harwich International",
    "Harwich Town",
    "Haslemere",
    "Hassocks",
    "Hastings",
    "Hatch End",
    "Hatfield",
    "Hatfield & Stainforth",
    "Hatfield Peverel",
    "Hathersage",
    "Hattersley",
    "Hatton",
    "Hatton Cross (Bus)",
    "Havant",
    "Havenhouse",
    "Haverfordwest",
    "Hawarden",
    "Hawarden Bridge",
    "Hawick (Bus)",
    "Hawkhead",
    "Haworth (Bus)",
    "Haydon Bridge",
    "Haydons Road",
    "Hayes (Kent)",
    "Hayes & Harlington",
    "Hayle",
    "Haymarket",
    "Haywards Heath",
    "Hazel Grove",
    "Headcorn",
    "Headingley",
    "Headstone Lane",
    "Heald Green",
    "Healing",
    "Heath High Level",
    "Heath Low Level",
    "Heathrow Airport T1 (Bus)",
    "Heathrow Airport T123",
    "Heathrow Airport T2 (Bus)",
    "Heathrow Airport T3 (Bus)",
    "Heathrow Airport T4",
    "Heathrow Airport T4 (Bus)",
    "Heathrow Airport T5",
    "Heathrow Airport T5 (Bus)",
    "Heathrow Central Bus Stn",
    "Heaton Chapel",
    "Hebden Bridge",
    "Heckington",
    "Hedge End",
    "Hednesford",
    "Heighington",
    "Helensburgh Central",
    "Helensburgh Upper",
    "Hellifield",
    "Helmsdale",
    "Helsby",
    "Helston (Bus)",
    "Hemel Hempstead",
    "Hendon",
    "Hengoed",
    "Henley-in-Arden",
    "Henley-on-Thames",
    "Hensall",
    "Hereford",
    "Herne Bay",
    "Herne Hill",
    "Hersham",
    "Hertford East",
    "Hertford North",
    "Hessle",
    "Heswall",
    "Hever",
    "Heworth",
    "Heworth (T & W Metro)",
    "Hexham",
    "Heyford",
    "Heysham Port",
    "High Barnet",
    "High Brooms",
    "High Street",
    "High Wycombe",
    "Higham",
    "Highams Park",
    "Highbridge & Burnham",
    "Highbury & Islington",
    "Hightown",
    "Hildenborough",
    "Hillfoot",
    "Hillington East",
    "Hillington West",
    "Hillside",
    "Hilsea",
    "Hinchley Wood",
    "Hinckley",
    "Hindley",
    "Hinton Admiral",
    "Hirwaun (Bus)",
    "Hitchin",
    "Hither Green",
    "Hockley",
    "Hoek Van Holland",
    "Hollingbourne",
    "Hollinwood",
    "Holmes Chapel",
    "Holmwood",
    "Holsworthy (Bus)",
    "Holton Heath",
    "Holyhead",
    "Holytown",
    "Homerton",
    "Honeybourne",
    "Honiton",
    "Honley",
    "Honor Oak Park",
    "Hook",
    "Hooton",
    "Hope (Derbyshire)",
    "Hope (Flintshire)",
    "Hopton Heath",
    "Horden",
    "Horley",
    "Hornbeam Park",
    "Hornsey",
    "Horsforth",
    "Horsham",
    "Horsley",
    "Horton-in-Ribblesdale",
    "Horwich Parkway",
    "Hoscar",
    "Hough Green",
    "Hounslow",
    "Hove",
    "Hoveton & Wroxham",
    "How Wood",
    "Howden",
    "Howwood",
    "Hoxton",
    "Hoylake",
    "Hubberts Bridge",
    "Hucknall",
    "Huddersfield",
    "Hull",
    "Hull (Bus)",
    "Humphrey Park",
    "Huncoat",
    "Hungerford",
    "Hunmanby",
    "Hunstanton (Bus)",
    "Huntingdon",
    "Huntly",
    "Hunts Cross",
    "Hursley Post Office (Bus)",
    "Hurst Green",
    "Hutton Cranswick",
    "Huyton",
    "Hyde Central",
    "Hyde North",
    "Hyde Park (Tram)",
    "Hykeham",
    "Hykeham Crossroads (Bus)",
    "Hyndland",
    "Hythe",
    "Hythe Waterside (Bus)",
    "IBM",
    "Ifield",
    "Ilford",
    "Ilkeston",
    "Ilkley",
    "Imperial Wharf",
    "Ince",
    "Ince & Elton",
    "Ingatestone",
    "Insch",
    "Invergordon",
    "Invergowrie",
    "Inverkeithing",
    "Inverkip",
    "Inverness",
    "Inverness Airport",
    "Invershin",
    "Inverurie",
    "Ipswich",
    "Irlam",
    "Irvine",
    "Isleworth",
    "Islip",
    "Iver",
    "Ivybridge",
    "James Cook",
    "James Street",
    "Jewellery Quarter",
    "Johnston",
    "Johnstone",
    "Jordanhill",
    "Kearsley",
    "Kearsney",
    "Keighley",
    "Keith",
    "Kelvedon",
    "Kelvindale",
    "Kemble",
    "Kempston Hardwick",
    "Kempton Park",
    "Kemsing",
    "Kemsley",
    "Kendal",
    "Kenilworth",
    "Kenley",
    "Kennett",
    "Kennishead",
    "Kensal Green",
    "Kensal Rise",
    "Kensington High St Underground",
    "Kensington Olympia",
    "Kent House",
    "Kentish Town",
    "Kentish Town West",
    "Kenton",
    "Kents Bank",
    "Keswick Bus Station",
    "Kettering",
    "Kettering (Bus)",
    "Kew Bridge",
    "Kew Gardens",
    "Keyham",
    "Keynsham",
    "Kidbrooke",
    "Kidderminster",
    "Kidsgrove",
    "Kidwelly",
    "Kilburn High Road",
    "Kilcreggan (Bus)",
    "Kildale",
    "Kildonan",
    "Kilgetty",
    "Kilmarnock",
    "Kilmaurs",
    "Kilpatrick",
    "Kilwinning",
    "Kinbrace",
    "Kingham",
    "Kinghorn",
    "Kings Langley",
    "Kings Lynn",
    "Kings Lynn Bus Station",
    "Kings Norton",
    "Kings Nympton",
    "Kings Park",
    "Kings Sutton",
    "Kingsbridge (Bus)",
    "Kingsknowe",
    "Kingston",
    "Kingswear",
    "Kingswood",
    "Kingussie",
    "Kintbury",
    "Kintore",
    "Kirby Cross",
    "Kirk Sandall",
    "Kirkby",
    "Kirkby in Ashfield",
    "Kirkby Stephen",
    "Kirkby-in-Furness",
    "Kirkcaldy",
    "Kirkconnel",
    "Kirkdale",
    "Kirkham & Wesham",
    "Kirkhill",
    "Kirknewton",
    "Kirkstall Forge",
    "Kirkwood",
    "Kirton Lindsey",
    "Kiveton Bridge",
    "Kiveton Park",
    "Knaresborough",
    "Knebworth",
    "Knighton",
    "Knockholt",
    "Knottingley",
    "Knucklas",
    "Knutsford",
    "Kyle of Lochalsh",
    "Kyleakin, Skye (Bus)",
    "Ladybank",
    "Ladywell",
    "Laindon",
    "Lairg",
    "Lake",
    "Lakenheath",
    "Lamphey",
    "Lanark",
    "Lancaster",
    "Lancing",
    "Landywood",
    "Langbank",
    "Langho",
    "Langholm (Bus)",
    "Langley",
    "Langley Green",
    "Langley Mill",
    "Langside",
    "Langwathby",
    "Langwith-Whaley Thorns",
    "Lapford",
    "Lapworth",
    "Larbert",
    "Largs",
    "Larkhall",
    "Larne Harbour (Bus)",
    "Launceston (Bus)",
    "Laurencekirk",
    "Lawrence Hill",
    "Layton",
    "Lazonby & Kirkoswald",
    "Lea Bridge",
    "Lea Green",
    "Lea Hall",
    "Leagrave",
    "Lealholm",
    "Leamington Spa",
    "Leasowe",
    "Leatherhead",
    "Ledbury",
    "Lee",
    "Leeds",
    "Leeds Bradford Airport (Bus)",
    "Leeds Festival  (Bus)",
    "Leeds, Whitehall (Bus)",
    "Leicester",
    "Leigh (Kent)",
    "Leigh-on-Sea",
    "Leighton Buzzard",
    "Lelant",
    "Lelant Saltings",
    "Lenham",
    "Lenzie",
    "Leominster",
    "Letchworth Garden City",
    "Leuchars",
    "Levenshulme",
    "Levisham",
    "Lewes",
    "Lewisham",
    "Leyland",
    "Leyton Midland Road",
    "Leytonstone High Road",
    "Lichfield City",
    "Lichfield Trent Valley",
    "Lidlington",
    "Lille Europe",
    "Limehouse",
    "Lincoln Bus Station",
    "Lincoln Central",
    "Lindford (Bus)",
    "Lingfield",
    "Lingwood",
    "Linlithgow",
    "Liphook",
    "Liskeard",
    "Lismore (Bus)",
    "Liss",
    "Lisvane & Thornhill",
    "Little Kimble",
    "Little Sutton",
    "Littleborough",
    "Littlehampton",
    "Littlehaven",
    "Littleport",
    "Liverpool Central",
    "Liverpool Landing Stage",
    "Liverpool Lime Street",
    "Liverpool South Parkway",
    "Livingston North",
    "Livingston South",
    "Llanaber",
    "Llanbedr",
    "Llanbister Road",
    "Llanbradach",
    "Llandaf",
    "Llandanwg",
    "Llandecwyn",
    "Llandeilo",
    "Llandovery",
    "Llandrindod",
    "Llandudno",
    "Llandudno Junction",
    "Llandybie",
    "Llanelli",
    "Llanfairfechan",
    "Llanfairpwll",
    "Llangadog",
    "Llangammarch",
    "Llangennech",
    "Llangynllo",
    "Llanharan",
    "Llanhilleth",
    "Llanishen",
    "Llanrwst",
    "Llansamlet",
    "Llantwit Major",
    "Llanwrda",
    "Llanwrtyd",
    "Llwyngwril",
    "Llwynypia",
    "Loch Awe",
    "Loch Eil Outward Bound",
    "Lochailort",
    "Lochboisdale, South Uist (Bus)",
    "Locheilside",
    "Lochgelly",
    "Lochluichart",
    "Lochmaddy, North Uist (Bus)",
    "Lochwinnoch",
    "Lockerbie",
    "Lockwood",
    "London Blackfriars",
    "London Bridge",
    "London Cannon Street",
    "London Charing Cross",
    "London Euston",
    "London Fenchurch Street",
    "London Fields",
    "London Kings Cross",
    "London Liverpool Street",
    "London Marylebone",
    "London Paddington",
    "London Road (Brighton)",
    "London Road (Guildford)",
    "London St Pancras (Intl)",
    "London Victoria",
    "London Waterloo",
    "London Waterloo East",
    "Long Buckby",
    "Long Eaton",
    "Long Preston",
    "Longbeck",
    "Longbridge",
    "Longcross",
    "Longfield",
    "Longniddry",
    "Longport",
    "Longton",
    "Looe",
    "Lostock",
    "Lostock Gralam",
    "Lostock Hall",
    "Lostwithiel",
    "Loughborough",
    "Loughborough Junction",
    "Low Moor",
    "Lowdham",
    "Lower Sydenham",
    "Lowestoft",
    "Ludlow",
    "Luton",
    "Luton (Bus)",
    "Luton Airport (Bus)",
    "Luton Airport Parkway",
    "Luxulyan",
    "Lydney",
    "Lye",
    "Lymington Pier",
    "Lymington Town",
    "Lympstone Commando",
    "Lympstone Village",
    "Lyneham Camp (Bus)",
    "Lytham",
    "Macclesfield",
    "Machynlleth",
    "Maesteg",
    "Maesteg (Ewenny Road)",
    "Maghull",
    "Maghull North",
    "Maiden Newton",
    "Maidenhead",
    "Maidstone Barracks",
    "Maidstone East",
    "Maidstone West",
    "Malden Manor",
    "Mallaig",
    "Malton",
    "Malvern Link",
    "Manchester Airport",
    "Manchester Oxford Road",
    "Manchester Piccadilly",
    "Manchester United FC",
    "Manchester Victoria",
    "Manea",
    "Manningtree",
    "Manor Park",
    "Manor Road",
    "Manorbier",
    "Manors",
    "Manors (T & W Metro)",
    "Mansfield",
    "Mansfield Woodhouse",
    "March",
    "Marden",
    "Margate",
    "Market Harborough",
    "Market Rasen",
    "Markinch",
    "Marks Tey",
    "Marlborough (Bus)",
    "Marlow",
    "Marne La Vallee",
    "Marple",
    "Marsden",
    "Marseille St Charles",
    "Marske",
    "Marston Green",
    "Martin Mill",
    "Martins Heron",
    "Marton",
    "Maryhill",
    "Maryland",
    "Maryport",
    "Matlock",
    "Matlock Bath",
    "Mauldeth Road",
    "Maxwell Park",
    "Maybole",
    "Maze Hill",
    "Meadowhall",
    "Meldreth",
    "Melksham",
    "Melksham Market Place (Bus)",
    "Melrose (Bus)",
    "Melton",
    "Melton Mowbray",
    "Menheniot",
    "Menston",
    "Meols",
    "Meols Cop",
    "Meopham",
    "Meridian Water",
    "Merryton",
    "Merstham",
    "Merthyr Tydfil",
    "Merthyr Vale",
    "Metheringham",
    "Metro Centre",
    "Mevagissey (Bus)",
    "Mexborough",
    "Micheldever",
    "Micklefield",
    "Middlesbrough",
    "Middlewood",
    "Midgham",
    "Midsomer Norton (Bus)",
    "Milford (Surrey)",
    "Milford Haven",
    "Mill Hill (Lancashire)",
    "Mill Hill Broadway",
    "Millbrook (Bedfordshire)",
    "Millbrook (Hampshire)",
    "Millfield (T & W Metro)",
    "Milliken Park",
    "Millom",
    "Mills Hill",
    "Milngavie",
    "Milnrow",
    "Milton Keynes Central",
    "Minehead",
    "Minehead (Bus)",
    "Minehead Butlins (Bus)",
    "Minffordd",
    "Minster",
    "Mirfield",
    "Mistley",
    "Mitcham Eastfields",
    "Mitcham Junction",
    "Mobberley",
    "Monifieth",
    "Monks Risborough",
    "Montpelier",
    "Montrose",
    "Moorfields",
    "Moorgate",
    "Moorside",
    "Moorthorpe",
    "Morar",
    "Morchard Road",
    "Morden South",
    "Morecambe",
    "Moreton (Dorset)",
    "Moreton (Merseyside)",
    "Moreton-in-Marsh",
    "Moretonhampstead (Bus)",
    "Morfa Mawddach",
    "Morley",
    "Morpeth",
    "Mortimer",
    "Mortlake",
    "Moses Gate",
    "Moss Side",
    "Mossley",
    "Mossley Hill",
    "Mosspark",
    "Moston",
    "Motherwell",
    "Motspur Park",
    "Mottingham",
    "Mottisfont & Dunbridge",
    "Mouldsworth",
    "Moulsecoomb",
    "Mount Florida",
    "Mount Vernon",
    "Mountain Ash",
    "Muck (Bus)",
    "Muir of Ord",
    "Muirend",
    "Musselburgh",
    "Mytholmroyd",
    "Nafferton",
    "Nailsea & Backwell",
    "Nairn",
    "Nantwich",
    "Narberth",
    "Narborough",
    "Navigation Road",
    "Neath",
    "Needham Market",
    "Neilston",
    "Nelson",
    "Neston",
    "Netherfield",
    "Nethertown",
    "Netley",
    "New Barnet",
    "New Beckenham",
    "New Brighton",
    "New Clee",
    "New Cross",
    "New Cross Gate",
    "New Cumnock",
    "New Eltham",
    "New Hey",
    "New Holland",
    "New Hythe",
    "New Lane",
    "New Malden",
    "New Mills Central",
    "New Mills Newtown",
    "New Milton",
    "New Pudsey",
    "New Southgate",
    "Newark Castle",
    "Newark North Gate",
    "Newbridge",
    "Newbury",
    "Newbury Park Underground",
    "Newbury Racecourse",
    "Newcastle",
    "Newcastle Airport",
    "Newcastle Central Metro",
    "Newcourt",
    "Newcraighall",
    "Newhaven Harbour",
    "Newhaven Marine (Bus)",
    "Newhaven Town",
    "Newington",
    "Newmarket",
    "Newport (Essex)",
    "Newport (South Wales)",
    "Newquay",
    "Newstead",
    "Newton",
    "Newton Abbot",
    "Newton Aycliffe",
    "Newton for Hyde",
    "Newton St Cyres",
    "Newton-le-Willows",
    "Newton-on-Ayr",
    "Newtongrange",
    "Newtonmore",
    "Newtown (Powys)",
    "Ninian Park",
    "Nitshill",
    "Norbiton",
    "Norbury",
    "Normans Bay",
    "Normanton",
    "North Berwick",
    "North Camp",
    "North Dulwich",
    "North Fambridge",
    "North Llanrwst",
    "North Queensferry",
    "North Road",
    "North Sheen",
    "North Walsham",
    "North Wembley",
    "Northallerton",
    "Northampton",
    "Northfield",
    "Northfleet",
    "Northolt Park",
    "Northumberland Park",
    "Northwich",
    "Norton Bridge",
    "Norton Bridge (Bus)",
    "Norwich",
    "Norwood Junction",
    "Nottingham",
    "Nuneaton",
    "Nunhead",
    "Nunnery Square (Tram)",
    "Nunthorpe",
    "Nutbourne",
    "Nutfield",
    "Nutfield Memorial Hall (Bus)",
    "Oakengates",
    "Oakham",
    "Oakleigh Park",
    "Oakwood LUL (Enfield)",
    "Oban",
    "Ockendon",
    "Ockley",
    "Okehampton",
    "Okehampton (Bus)",
    "Old Hill",
    "Old Roan",
    "Old Street",
    "Oldfield Park",
    "Oldham Mumps",
    "Oldham Werneth",
    "Olton",
    "Ore",
    "Ormskirk",
    "Orpington",
    "Orrell",
    "Orrell Park",
    "Otford",
    "Otley Bus Station",
    "Oulton Broad North",
    "Oulton Broad South",
    "Oundle Market Place (Bus)",
    "Outwood",
    "Overpool",
    "Overton",
    "Oxenholme Lake District",
    "Oxenhope",
    "Oxford",
    "Oxford Parkway",
    "Oxshott",
    "Oxted",
    "Paddock Wood",
    "Padgate",
    "Padstow Bus Terminus",
    "Paignton",
    "Paisley Canal",
    "Paisley Gilmour Street",
    "Paisley St James",
    "Pallion (T & W Metro)",
    "Palmers Green",
    "Pangbourne",
    "Pannal",
    "Pantyffynnon",
    "Par",
    "Par (Bus)",
    "Parbold",
    "Paris Nord",
    "Park Lane (Bus)",
    "Park Street",
    "Parkgate",
    "Parkstone (Dorset)",
    "Parson Street",
    "Partick",
    "Parton",
    "Patchway",
    "Patricroft",
    "Patterton",
    "Peartree",
    "Peckham Rye",
    "Peebles Bus Stop",
    "Pegswood",
    "Pelaw (T & W Metro)",
    "Pemberton",
    "Pembrey & Burry Port",
    "Pembroke",
    "Pembroke Dock",
    "Pembroke Dock Ferry Term",
    "Pen-y-bont",
    "Penally",
    "Penarth",
    "Pencoed",
    "Pengam",
    "Penge East",
    "Penge West",
    "Penhelig",
    "Penistone",
    "Penkridge",
    "Penmaenmawr",
    "Penmere",
    "Penrhiwceiber",
    "Penrhyndeudraeth",
    "Penrith",
    "Penryn",
    "Pensarn",
    "Penshurst",
    "Pentre-bach",
    "Penychain",
    "Penyffordd",
    "Penywaun (Bus)",
    "Penzance",
    "Perranporth (Bus)",
    "Perranwell",
    "Perry Barr",
    "Pershore",
    "Perth",
    "Peterborough",
    "Peterborough Queensgate (Bus)",
    "Petersfield",
    "Petts Wood",
    "Pevensey & Westham",
    "Pevensey Bay",
    "Pewsey",
    "Piccadilly Circus Underground",
    "Pickering",
    "Pickering Eastgate (Bus)",
    "Pilning",
    "Pinhoe",
    "Pitlochry",
    "Pitsea",
    "Plaistow",
    "Pleasington",
    "Plockton",
    "Pluckley",
    "Plumley",
    "Plumpton",
    "Plumstead",
    "Plymouth",
    "Plymouth Saltash Road (Bus)",
    "Pokesdown",
    "Polegate",
    "Polesworth",
    "Pollokshaws East",
    "Pollokshaws West",
    "Pollokshields East",
    "Pollokshields West",
    "Polmont",
    "Polsloe Bridge",
    "Ponders End",
    "Pont-y-Pant",
    "Pontarddulais",
    "Pontefract Baghill",
    "Pontefract Monkhill",
    "Pontefract Tanshelf",
    "Pontlottyn",
    "Pontyclun",
    "Pontypool & New Inn",
    "Pontypridd",
    "Poole",
    "Poppleton",
    "Port Glasgow",
    "Port Sunlight",
    "Port Talbot Parkway",
    "Portchester",
    "Porth",
    "Porthcawl (Bus)",
    "Porthmadog",
    "Porthmadog Harbour  (Bus)",
    "Portlethen",
    "Portslade",
    "Portsmouth & Southsea",
    "Portsmouth Arms",
    "Portsmouth Harbour",
    "Possilpark & Parkhouse",
    "Potters Bar",
    "Poulton-le-Fylde",
    "Poynton",
    "Prees",
    "Prescot",
    "Prestatyn",
    "Prestbury",
    "Preston",
    "Preston C S (Ferry)",
    "Preston Park",
    "Prestonpans",
    "Prestwich Metrolink (Bus)",
    "Prestwick Intl Airport",
    "Prestwick Town",
    "Priesthill & Darnley",
    "Princes Risborough",
    "Princetown (Bus)",
    "Prittlewell",
    "Private Charter",
    "Prudhoe",
    "Pulborough",
    "Purfleet",
    "Purley",
    "Purley Oaks",
    "Putney",
    "Pwllheli",
    "Pye Corner",
    "Pyle",
    "Quainton Road",
    "Quakers Yard",
    "Queenborough",
    "Queens Park (Glasgow)",
    "Queens Park (London)",
    "Queens Road Peckham",
    "Queenstown Road Battersea",
    "Quintrell Downs",
    "Radcliffe (Nottinghamshire)",
    "Radcliffe Metrolink (Bus)",
    "Radlett",
    "Radley",
    "Radstock (Bus)",
    "Radyr",
    "Rainford",
    "Rainham (Essex)",
    "Rainham (Kent)",
    "Rainhill",
    "Ramsgate",
    "Ramsgate Harbour (Bus)",
    "Ramsgreave & Wilpshire",
    "Rannoch",
    "Rauceby",
    "Ravenglass for Eskdale",
    "Ravensbourne",
    "Ravensthorpe",
    "Rawcliffe",
    "Rayleigh",
    "Raynes Park",
    "Reading",
    "Reading West",
    "Rectory Road",
    "Redbridge",
    "Redcar Central",
    "Redcar East",
    "Reddish North",
    "Reddish South",
    "Redditch",
    "Redhill",
    "Redland",
    "Redruth",
    "Reedham (Norfolk)",
    "Reedham (Surrey)",
    "Regent Centre (Bus)",
    "Reigate",
    "Renton",
    "Reston",
    "Retford",
    "Rhigos (Bus)",
    "Rhiwbina",
    "Rhoose Cardiff Intl Airport",
    "Rhosneigr",
    "Rhum (Bus)",
    "Rhyl",
    "Rhymney",
    "Rhymney Tredegar (Bus)",
    "Ribblehead",
    "Rice Lane",
    "Richmond",
    "Richmond, Nth Yorks (Bus)",
    "Rickmansworth",
    "Riddlesdown",
    "Ridgmont",
    "Riding Mill",
    "Risca & Pontymister",
    "Rishton",
    "Robertsbridge",
    "Robin Hood Airport (Bus)",
    "Robroyston",
    "Roby",
    "Rochdale",
    "Roche",
    "Rochester",
    "Rochford",
    "Rock Ferry",
    "Rogart",
    "Rogerstone",
    "Rolleston",
    "Roman Bridge",
    "Romford",
    "Romiley",
    "Romsey",
    "Romsey Bus Station",
    "Roose",
    "Rose Grove",
    "Rose Hill Marple",
    "Rosslare Europort",
    "Rosyth",
    "Rotherham Central",
    "Rotherhithe",
    "Rothesay, Bute (Bus)",
    "Roughton Road",
    "Rowlands Castle",
    "Rowley Regis",
    "Roy Bridge",
    "Roydon",
    "Royston",
    "Ruabon",
    "Rufford",
    "Rugby",
    "Rugeley Town",
    "Rugeley Trent Valley",
    "Runcorn",
    "Runcorn East",
    "Ruskington",
    "Ruswarp",
    "Rutherglen",
    "Ryde Esplanade",
    "Ryde Pier Head",
    "Ryde St Johns Road",
    "Ryder Brow",
    "Rye",
    "Rye House",
    "Sale Metrolink (Bus)",
    "Salford Central",
    "Salford Crescent",
    "Salfords",
    "Salhouse",
    "Salisbury",
    "Saltaire",
    "Saltash",
    "Saltburn",
    "Saltcoats",
    "Saltmarshe",
    "Salwick",
    "Sampford Courtenay",
    "Sandal & Agbrigg",
    "Sandbach",
    "Sanderstead",
    "Sandhills",
    "Sandhurst",
    "Sandling",
    "Sandown",
    "Sandplace",
    "Sandringham (Bus)",
    "Sandwell & Dudley",
    "Sandwich",
    "Sandy",
    "Sankey for Penketh",
    "Sanquhar",
    "Sarn",
    "Saundersfoot",
    "Saunderton",
    "Sawbridgeworth",
    "Saxilby",
    "Saxmundham",
    "Scarborough",
    "Scotscalder",
    "Scotstounhill",
    "Scrabster (Bus)",
    "Scunthorpe",
    "Sea Mills",
    "Seaburn (T & W Metro)",
    "Seaford",
    "Seaforth & Litherland",
    "Seaham",
    "Seamer",
    "Seascale",
    "Seaton Carew",
    "Seaton, Devon (Bus)",
    "Seer Green",
    "Selby",
    "Selhurst",
    "Selkirk (Bus)",
    "Sellafield",
    "Selling",
    "Selly Oak",
    "Settle",
    "Seven Kings",
    "Seven Sisters",
    "Sevenoaks",
    "Severn Beach",
    "Severn Tunnel Junction",
    "Shadwell",
    "Shaftesbury Town Hall (Bus)",
    "Shalford",
    "Shanklin",
    "Shaw & Crompton",
    "Shawfair",
    "Shawford",
    "Shawlands",
    "Sheerness-on-Sea",
    "Sheffield",
    "Sheffield Arena (Tram)",
    "Sheffield Cathedral(Tram)",
    "Shelford",
    "Shenfield",
    "Shenstone",
    "Shepherds Bush",
    "Shepherds Well",
    "Shepley",
    "Shepperton",
    "Shepreth",
    "Sherborne",
    "Sherburn-in-Elmet",
    "Sheringham",
    "Shettleston",
    "Shieldmuir",
    "Shifnal",
    "Shildon",
    "Shiplake",
    "Shipley",
    "Shippea Hill",
    "Shipton",
    "Shirebrook",
    "Shirehampton",
    "Shireoaks",
    "Shirley",
    "Shoeburyness",
    "Sholing",
    "Shoreditch High Street",
    "Shoreham (Kent)",
    "Shoreham-by-Sea",
    "Shortlands",
    "Shotton",
    "Shotts",
    "Shrewsbury",
    "Sidcup",
    "Sileby",
    "Silecroft",
    "Silkstone Common",
    "Silver Street",
    "Silverdale",
    "Singer",
    "Sittingbourne",
    "Skegness",
    "Skewen",
    "Skipton",
    "Slade Green",
    "Slaithwaite",
    "Slateford",
    "Sleaford",
    "Sleights",
    "Slough",
    "Small Heath",
    "Smallbrook Junction",
    "Smethwick Galton Bridge",
    "Smethwick Rolfe Street",
    "Smithy Bridge",
    "Snaith",
    "Snodland",
    "Snowdown",
    "Soham",
    "Sole Street",
    "Solihull",
    "Somerleyton",
    "South Acton",
    "South Bank",
    "South Bermondsey",
    "South Croydon",
    "South Elmsall",
    "South Gosforth (T & W Metro)",
    "South Greenford",
    "South Gyle",
    "South Hampstead",
    "South Hylton (T & W Metro)",
    "South Kenton",
    "South Merton",
    "South Milford",
    "South Ruislip",
    "South Tottenham",
    "South Wigston",
    "South Woodham Ferrers",
    "Southall",
    "Southampton Airport Parkway",
    "Southampton Central",
    "Southampton Eastern Docks",
    "Southampton Town Quay (Bus)",
    "Southampton Western Docks",
    "Southbourne",
    "Southbury",
    "Southease",
    "Southend Airport",
    "Southend Central",
    "Southend East",
    "Southend Victoria",
    "Southminster",
    "Southport",
    "Southport, Lord Street (Bus)",
    "Southsea Hoverport (Bus)",
    "Southwell (Bus)",
    "Southwick",
    "Sowerby Bridge",
    "Spalding",
    "Spean Bridge",
    "Spital",
    "Spondon",
    "Spooner Row",
    "Spring Road",
    "Springburn",
    "Springfield",
    "Squires Gate",
    "St Albans",
    "St Albans Abbey",
    "St Andrews (Bus)",
    "St Andrews Road",
    "St Annes-on-the-Sea",
    "St Austell",
    "St Bees",
    "St Budeaux Ferry Road",
    "St Budeaux Victoria Road",
    "St Columb Road",
    "St Denys",
    "St Erth",
    "St Germans",
    "St Helens Central",
    "St Helens Junction",
    "St Helier",
    "St Ives",
    "St James (T & W Metro)",
    "St James Street",
    "St James' Park",
    "St Johns",
    "St Keyne Wishing Well Halt",
    "St Leonards Warrior Square",
    "St Margarets (Hertfordshire)",
    "St Margarets (London)",
    "St Mary Cray",
    "St Michaels",
    "St Neots",
    "St Neots (Bus)",
    "St Peters (T & W Metro)",
    "Stadium of Light (T & W Metro)",
    "Stafford",
    "Staines",
    "Stallingborough",
    "Stalybridge",
    "Stamford",
    "Stamford Hill",
    "Stanford-le-Hope",
    "Stanhope",
    "Stanlow & Thornton",
    "Stansted Airport",
    "Stansted Airport Bus Stop",
    "Stansted Mountfitchet",
    "Staplehurst",
    "Stapleton Road",
    "Starbeck",
    "Starcross",
    "Staveley",
    "Stechford",
    "Steeton & Silsden",
    "Stepps",
    "Stevenage",
    "Stevenston",
    "Stewartby",
    "Stewarton",
    "Stirling",
    "Stockport",
    "Stocksfield",
    "Stocksmoor",
    "Stockton",
    "Stoke Mandeville",
    "Stoke Newington",
    "Stoke-on-Trent",
    "Stone",
    "Stone Crossing",
    "Stone Crown Street (Bus)",
    "Stone Granville Square (Bus)",
    "Stonebridge Park",
    "Stonegate",
    "Stonehaven",
    "Stonehouse",
    "Stoneleigh",
    "Stornoway, Lewis (Bus)",
    "Stourbridge Junction",
    "Stourbridge Town",
    "Stow",
    "Stowmarket",
    "Stranraer",
    "Stranraer West Pier (Bus)",
    "Stratford (London)",
    "Stratford International",
    "Stratford Parkway",
    "Stratford-upon-Avon",
    "Strathcarron",
    "Strawberry Hill",
    "Streatham",
    "Streatham Common",
    "Streatham Hill",
    "Street (Bus)",
    "Streethouse",
    "Stretford Metrolink (Bus)",
    "Strines",
    "Stromeferry",
    "Strood",
    "Stroud",
    "Sturry",
    "Styal",
    "Sudbury",
    "Sudbury & Harrow Road",
    "Sudbury Hill Harrow",
    "Sugar Loaf",
    "Summerston",
    "Sunbury",
    "Sunderland",
    "Sundridge Park",
    "Sunningdale",
    "Sunnymeads",
    "Surbiton",
    "Surrey Quays",
    "Sutton (London)",
    "Sutton Coldfield",
    "Sutton Common",
    "Sutton Parkway",
    "Swaffham Tourist Inf Ctr (Bus)",
    "Swale",
    "Swanley",
    "Swanscombe",
    "Swansea",
    "Swansea Docks (Bus)",
    "Swanwick",
    "Sway",
    "Swaythling",
    "Swinderby",
    "Swinderby A46 Roundabout (Bus)",
    "Swindon",
    "Swindon Bus Station",
    "Swineshead",
    "Swinton (Manchester)",
    "Swinton (South Yorkshire)",
    "Sydenham",
    "Sydenham Hill",
    "Syon Lane",
    "Syston",
    "Tackley",
    "Tadworth",
    "Taffs Well",
    "Tain",
    "Tal-y-Cafn",
    "Talsarnau",
    "Talybont",
    "Tame Bridge Parkway",
    "Tamworth",
    "Tan-y-Bwlch  (Bus)",
    "Taplow",
    "Tarbert, Harris (Bus)",
    "Tattenham Corner",
    "Taunton",
    "Taunton (Bus)",
    "Tavistock (Bus)",
    "Taynuilt",
    "Teddington",
    "Tees Valley Airport (Bus)",
    "Tees-side Airport",
    "Teignmouth",
    "Telford Central",
    "Templecombe",
    "Tenby",
    "Teynham",
    "Thames Ditton",
    "Thatcham",
    "Thatto Heath",
    "The Hawthorns",
    "The Lakes",
    "Theale",
    "Theobalds Grove",
    "Thetford",
    "Thirsk",
    "Thornaby",
    "Thorne North",
    "Thorne South",
    "Thornford",
    "Thornliebank",
    "Thornton Abbey",
    "Thornton Heath",
    "Thorntonhall",
    "Thorpe Bay",
    "Thorpe Culvert",
    "Thorpe-le-Soken",
    "Three Bridges",
    "Three Oaks",
    "Thurgarton",
    "Thurnscoe",
    "Thurso",
    "Thurston",
    "Tilbury Riverside (Bus)",
    "Tilbury Town",
    "Tile Hill",
    "Tilehurst",
    "Tinsley Meadowhall (Tram)",
    "Tintagel (Bus)",
    "Tipton",
    "Tir-phil",
    "Tiree (Bus)",
    "Tisbury",
    "Tiverton (Bus)",
    "Tiverton Parkway",
    "Tobermory, Mull (Bus)",
    "Todmorden",
    "Tolworth",
    "Ton Pentre",
    "Tonbridge",
    "Tondu",
    "Tonfanau",
    "Tonypandy",
    "Tooting",
    "Topsham",
    "Torquay",
    "Torre",
    "Totnes",
    "Tottenham Court Road",
    "Tottenham Hale",
    "Totton",
    "Tower Hill Underground",
    "Town Green",
    "Trafford Park",
    "Trecynon (Bus)",
    "Trefforest",
    "Trefforest Estate",
    "Trehafod",
    "Treherbert",
    "Treorchy",
    "Trimley",
    "Tring",
    "Troed-y-rhiw",
    "Troon",
    "Trowbridge",
    "Truro",
    "Tulloch",
    "Tulse Hill",
    "Tunbridge Wells",
    "Turkey Street",
    "Turnham Green Underground",
    "Turnpike Lane",
    "Tutbury & Hatton",
    "Tweedbank",
    "Twickenham",
    "Twyford",
    "Ty Croes",
    "Ty Glas",
    "Tygwyn",
    "Tyndrum Lower",
    "Tynemouth (T & W Metro)",
    "Tyseley",
    "Tywyn",
    "Uckfield",
    "Uddingston",
    "Uig, Skye (Bus)",
    "Ulceby",
    "Ullapool (Bus)",
    "Ulleskelf",
    "Ulverston",
    "Umberleigh",
    "University",
    "University (T & W Metro)",
    "Uphall",
    "Upholland",
    "Upminster",
    "Upminster Underground",
    "Upper Halliford",
    "Upper Holloway",
    "Upper Tyndrum",
    "Upper Warlingham",
    "Upton",
    "Upwey",
    "Urmston",
    "Uttoxeter",
    "Valley",
    "Valley Centertainment (Tram)",
    "Vauxhall",
    "Virginia Water",
    "Waddon",
    "Wadebridge Bus Station",
    "Wadhurst",
    "Wainfleet",
    "Wakefield Kirkgate",
    "Wakefield Westgate",
    "Walkden",
    "Wallasey Grove Road",
    "Wallasey Village",
    "Wallingford Market Place (Bus)",
    "Wallington",
    "Wallyford",
    "Walmer",
    "Walsall",
    "Walsden",
    "Waltham Cross",
    "Walthamstow Central",
    "Walthamstow Queens Road",
    "Walton (Merseyside)",
    "Walton-on-Thames",
    "Walton-on-the-Naze",
    "Wanborough",
    "Wandsworth Common",
    "Wandsworth Road",
    "Wandsworth Town",
    "Wanstead Park",
    "Wantage (Bus)",
    "Wapping",
    "Warblington",
    "Ware",
    "Wareham",
    "Wargrave",
    "Warminster",
    "Warnham",
    "Warrington Bank Quay",
    "Warrington Central",
    "Warrington West",
    "Warwick",
    "Warwick Parkway",
    "Warwick University (Bus)",
    "Watchet (Bus)",
    "Water Orton",
    "Waterbeach",
    "Wateringbury",
    "Waterloo (Merseyside)",
    "Waterloo Underground",
    "Watford High Street",
    "Watford Junction",
    "Watford North",
    "Watlington",
    "Watton-at-Stone",
    "Waun-gron Park",
    "Wavertree Tech Park",
    "Wedgwood",
    "Wedgwood Old Road Bridge (Bus)",
    "Weeley",
    "Weeton",
    "Welham Green",
    "Welling",
    "Wellingborough",
    "Wellington (Shropshire)",
    "Wells (Bus)",
    "Wells-Next-The-Sea (Bus)",
    "Welshpool",
    "Welwyn Garden City",
    "Welwyn North",
    "Wem",
    "Wembley Central",
    "Wembley Stadium",
    "Wemyss Bay",
    "Wendover",
    "Wennington",
    "West Allerton",
    "West Brompton",
    "West Byfleet",
    "West Calder",
    "West Croydon",
    "West Drayton",
    "West Dulwich",
    "West Ealing",
    "West Ham",
    "West Hampstead",
    "West Hampstead Thameslink",
    "West Horndon",
    "West Kilbride",
    "West Kirby",
    "West Malling",
    "West Norwood",
    "West Ruislip",
    "West Runton",
    "West St Leonards",
    "West Sutton",
    "West Wickham",
    "West Worthing",
    "Westbury",
    "Westbury (Bus)",
    "Westcliff",
    "Westcombe Park",
    "Westenhanger",
    "Wester Hailes",
    "Westerfield",
    "Westerton",
    "Westgate-on-Sea",
    "Westhoughton",
    "Weston Milton",
    "Weston-super-Mare",
    "Wetheral",
    "Weybridge",
    "Weymouth",
    "Weymouth Quay (Bus)",
    "Whaley Bridge",
    "Whalley",
    "Whatstandwell",
    "Whifflet",
    "Whimple",
    "Whinhill",
    "Whiston",
    "Whitby",
    "Whitby Bus Station",
    "Whitchurch (Glamorgan)",
    "Whitchurch (Hampshire)",
    "Whitchurch (Shropshire)",
    "White Hart Lane",
    "White Notley",
    "Whitechapel",
    "Whitecraigs",
    "Whitehaven",
    "Whitehill Prince of Wales (Bus",
    "Whitland",
    "Whitley Bridge",
    "Whitlocks End",
    "Whitstable",
    "Whittlesea",
    "Whittlesford Parkway",
    "Whitton",
    "Whitwell",
    "Whyteleafe",
    "Whyteleafe South",
    "Wick",
    "Wickford",
    "Wickham Market",
    "Widdrington",
    "Widnes",
    "Widney Manor",
    "Wigan North Western",
    "Wigan Wallgate",
    "Wigton",
    "Wildmill",
    "Willesden Junction",
    "Williamwood",
    "Willington",
    "Wilmcote",
    "Wilmslow",
    "Wilnecote",
    "Wimbledon",
    "Wimbledon Chase",
    "Winchelsea",
    "Winchester",
    "Winchfield",
    "Winchmore Hill",
    "Windermere",
    "Windsor & Eton Central",
    "Windsor & Eton Riverside",
    "Winnersh",
    "Winnersh Triangle",
    "Winsford",
    "Wisbech Horsefair (Bus)",
    "Wishaw",
    "Witham",
    "Witley",
    "Witney Market Place (Bus)",
    "Witton",
    "Wivelsfield",
    "Wivenhoe",
    "Woburn Sands",
    "Woking",
    "Wokingham",
    "Woldingham",
    "Wolverhampton",
    "Wolverton",
    "Wombwell",
    "Wood End",
    "Wood Street",
    "Woodbridge",
    "Woodburn Road (Tram)",
    "Woodgrange Park",
    "Woodhall",
    "Woodhouse",
    "Woodlesford",
    "Woodley",
    "Woodley, Hunters Inn (Bus)",
    "Woodmansterne",
    "Woodsmoor",
    "Wool",
    "Woolston",
    "Woolwich (Elizabeth line)",
    "Woolwich Arsenal",
    "Woolwich Dockyard",
    "Wootton Bassett (Bus)",
    "Wootton Wawen",
    "Worcester Foregate Street",
    "Worcester Park",
    "Worcester Shrub Hill",
    "Worcestershire Parkway",
    "Workington",
    "Workington Bus Station",
    "Worksop",
    "Worle",
    "Worplesdon",
    "Worstead",
    "Worthing",
    "Wrabness",
    "Wraysbury",
    "Wrenbury",
    "Wressle",
    "Wrexham Central",
    "Wrexham General",
    "Wye",
    "Wylam",
    "Wylde Green",
    "Wymondham",
    "Wythall",
    "Yalding",
    "Yardley Wood",
    "Yarm",
    "Yarmouth (Isle of Wight)",
    "Yate",
    "Yatton",
    "Yeoford",
    "Yeovil Bus Station",
    "Yeovil Junction",
    "Yeovil Pen Mill",
    "Yetminster",
    "Ynyswen",
    "Yoker",
    "York",
    "Yorton",
    "Ystrad Mynach",
    "Ystrad Rhondda"];